### ISSUE TITLE
Diagram In Table and Table In Diagram Support

### ISSUE THREAD

**Issue by sirinath** [bpmn-io/diagram-js#106]
Can you add integrations with https://github.com/dmn-io/table-js/

**Comment by nikku** [comment]
I have already commented on dmn-io/table-js#1. In general this is too broad of a feature to _just provide_ it. We will work on it if there exist specific use cases that require an integration.

For the mean time, you may work yourself through the projects and integrate them with each other yourself. Given that both are quite extensible it should be possible to provide a community extension for it.
