### ISSUE TITLE
Allow shape resizing by dragging edges

### ISSUE THREAD

**Issue by pedesen** [bpmn-io/diagram-js#117]
It should be possible to resize a shape in one dimension (vertically or horizontally) by dragging the edge.

On hover over an edge, a horizontal/vertical resize cursor should be shown (even if the element is not selected).

**Comment by FlexiGit** [comment]
The resize functionality should be configurable (enable/disable).

**Comment by philippfromme** [comment]
@FlexiGit resizing is actually configurable using rules that allow or disallow it. You can learn more about rules in [this example](https://github.com/bpmn-io/bpmn-js-examples/tree/master/custom-modeling-rules).
