### ISSUE TITLE
Move the canvas by getting close to the screen borders

### ISSUE THREAD

**Issue by nikku** [bpmn-io/diagram-js#121]
This is especially handy when navigating huge diagrams.

When modeling, i.e. creating a connection or moving an element this mechanism could be used to connect elements far out of range.

__Requirements:__

* [ ] getting close to the diagram border (with the mouse) moves the canvas in the appropriate direction
* [ ] this works while dragging, too

**Comment by nikku** [comment]
This may be annoying, too.

Alternative:  Indicate to the user via a clickable arrow that he can scroll (when getting close to canvas borders).

**Comment by nikku** [comment]
@vkatushenok We decided to close this in favor of move-on-border-during-dragging-only?

**Comment by vkatushenok** [comment]
@nikku We decided to postpone decision at that time. 

But I think this would be very annoying or not much useful, especially if we get [minimap](https://github.com/bpmn-io/bpmn-js/issues/501) implemented. 

Then dragging on minimap would be much easier and less disturbing.

So, think we should close it and open new issue, once there is really a need for such functionality.

**Comment by nikku** [comment]
All right. Going to close this.
