### ISSUE TITLE
Add infrastructur to allow copy + paste on the diagram

### ISSUE THREAD

**Issue by nikku** [bpmn-io/diagram-js#123]
Users should be able to copy and paste elements on the diagram.

Work on this ticket should lay down the foundations for editors to build copy and paste functionality.

Stuff that will generally be editor specific / should be customizable by editors:

* decide if a current selection can be copied
* decide if a selection can be pasted into a target selection
* perform the actual copy operation for each element

Stuff that can be implemented on the diagram:

* perform copy
* remember copy selection
* perform paste (duplicate selection and add it to target)

Links: 

* [bpmn.io forum thread](https://forum.bpmn.io/t/how-to-implement-copy-paste-feature-on-diagram-elements/312)

**Comment by ricardomatias** [comment]
What happens when the user wants to paste the items more than once ? Should we clone the elements ourselves and update their IDs ?

**Comment by nikku** [comment]
We should always copy all elements in the selection, making sure that a selection can be pasted multiple times.

@adrobisch Any updates on your efforts to implement this?

**Comment by adrobisch** [comment]
@nikku nope, I am currently working on a graphml based editor with diagram-js and wanted to tackle this as part of this effort. But I am still stuck with other issues there (like getting bendpoints to work). So there is nothing to contribute yet, feel free to overtake me ;-)

**Comment by adrobisch** [comment]
<3

**Comment by nikku** [comment]
:grinning: :tada:
