### ISSUE TITLE
deprecated dependencies @lodash

### ISSUE THREAD

**Issue by eriknyk** [bpmn-io/diagram-js#133]
Using node.js v5 I'm getting th efollowing deprecation warnings:

```
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
npm WARN deprecated lodash@0.9.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
npm WARN optional dep failed, continuing fsevents@1.0.5
npm WARN optional dep failed, continuing fsevents@1.0.5
```

Regards.

**Comment by nikku** [comment]
When are you seeing these errors? During `npm install` in development setup?

This is due to the fact that some libraries, including `grunt` use ancient versions of `lodash`. Nothing to be worried about.

It was a bug, if this project was relying on `lodash@<3.0.0` as a runtime dependency.
