### ISSUE TITLE
Question: Is it posible to export the model in JSON format? 

### ISSUE THREAD

**Issue by rubenjgarcia** [bpmn-io/diagram-js#135]
I wonder if there is a way to export the model in JSON format. I can use xml2js o sax but I wan't to know first if there is already an implemented way

Thanks

**Comment by nikku** [comment]
`diagram-js` does not have own facilities for exporting the shape hierarchy (neither XML nor JSON).

Projects building on top of it, i.e. [bpmn-js](https://github.com/bpmn-io/bpmn-js) are performing an XML export of their own internal data format.

**Comment by rubenjgarcia** [comment]
Thanks
