### ISSUE TITLE
Allow cursor to be changed with keybindings

### ISSUE THREAD

**Issue by ricardomatias** [bpmn-io/diagram-js#136]
This is related to features like the lasso and hand tool. It would allow us to straight away give feedback to the user on what behaviour is about to happen.
- Keyboard feature should be able to bind keyup events (or any type)

**Comment by nikku** [comment]
I added some changes on the [136-cursor-change-nikku branch](https://github.com/bpmn-io/diagram-js/tree/136-cursor-change-nikku) .

As discussed we need to rethink the way we work with tools / interactions during dragging. My changes resolve some issues (blinking of selection, getting `h` to work reliably but introduce new ones :-(.

I.e. on my branch we cannot get `h` to work _and_ toggling tools on the palette.
