### ISSUE TITLE
A little help getting the examples to run

### ISSUE THREAD

**Issue by heidi-de** [bpmn-io/diagram-js#140]
I have built the project with grunt but it is not helping with the examples. When firing up the HTML in a browser it complains about missing common.js and diagram.js. What else needs to be done? There seems to be some references on the web to requirejs and browserify in order be able to use "require" in JS in a browser environment. Have tried using these but still cannot get it to work correctly.
Any help would be greatly appreciated

**Comment by nikku** [comment]
What do you need in terms of examples? What would you like to do?

We are heavy lacking examples of how to build modeling tools around diagram-js but depending on your needs we may be able to help you out!
