### ISSUE TITLE
Throw exception when invoking the command stack in <execute> and <revert> phases

### ISSUE THREAD

**Issue by ricardomatias** [bpmn-io/diagram-js#143]
Inside `execute` and `revert` one must not schedule any other modeling operation, i.e. invoke `CommandStack#execute(...)`. This is due to the way how command composition (`preExecute` and `postExecute` phases as well as execution (`execute` and `revert` phases) works. 

Not taking that into account leads to invisible stack corruption and causes successive undo / redo operation to fail in most unexpected ways.

We should detect these situations and guard against wrong usage by throwing a descriptive exception inside `#execute`.

See [forum thread](https://forum.bpmn.io/t/503).

**Comment by nikku** [comment]
Which branch should I look into for a solution?

**Comment by ricardomatias** [comment]
It's in diagram-js, 143-execute-exception.

________________________________
