### ISSUE TITLE
Wrong position for attached shapes after using space tool

### ISSUE THREAD

**Issue by pedesen** [bpmn-io/diagram-js#155]
Attached shapes have a wrong position after the host gets **resized** using the space tool.
![spacetool](https://cloud.githubusercontent.com/assets/2543743/14285800/25dd55a4-fb4d-11e5-907f-3eb49a56205d.gif)
The screencast shows the unexpected behavior for boundary events in bpmn-js. It also affects sentries in cmmn-js.

**Comment by nikku** [comment]
That makes the space tool in bpmn-js / cmmn-js effectively unusable.
