### ISSUE TITLE
Palette item states are not consistent

### ISSUE THREAD

**Issue by vkatushenok** [bpmn-io/diagram-js#157]
When selecting tools/items on the palette, switching from one to another does not behave consistently.

E.g. actitions in sequence: 
1. select hand tool -> hand tool activated
2. select StartEvent -> item activated
3. select IntermediateThrowEvent -> `deactivated`

**Comment by vladimirskatusenoks** [comment]
Relates to #156: switching state of the tool is not always consistent

**Comment by vkatushenok** [comment]
Fixed with [commit](https://github.com/bpmn-io/diagram-js/commit/34a807e4a63af067b8f2bede7cbfb40aadf4e37d).
