### ISSUE TITLE
Remove the selection outline from within the base-layer svg group

### ISSUE THREAD

**Issue by ricardomatias** [bpmn-io/diagram-js#161]
This will allow us to create a minimap that uses native SVG mirroring

**Comment by ricardomatias** [comment]
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use

**Comment by ricardomatias** [comment]
Related to bpmn-io/bpmn-js#535

**Comment by philippfromme** [comment]
This is not necessary anymore. minimap has been implemented without the need to remove outline.

See bpmn-io/bpmn-js#535 for minimap implementation.
