### ISSUE TITLE
Always show the context menu when an element is selected

### ISSUE THREAD

**Issue by ricardomatias** [bpmn-io/diagram-js#163]
This would allow users to model in 'birds-eye' view.

Possible solution:
- always show the context menu when an element is selected
- the contents should have as minimum size, a similar size to the palette
- while zooming in the contents should slightly increase in order to provide some accessibility support

**Comment by berndruecker** [comment]
I like! Miss that pretty often

**Comment by nikku** [comment]
Context pad won't hide anymore via bpmn-io/diagram-js#229.
