### ISSUE TITLE
Exporting as SVG ignores marker style

### ISSUE THREAD

**Issue by vkatushenok** [bpmn-io/diagram-js#168]
**Steps to reproduce**
- create task with id `Task_123`
- add style similar to this:
```
.red:not(.djs-connection) .djs-visual > :nth-child(1) {
  fill: red !important;
}
```
- apply marker to an element:
```
canvas.addMarker( 'Task_123', 'red')
```
- export diagram as SVG

**Result**
Task body color should be red

See [original post](https://forum.bpmn.io/t/download-as-svg-with-colored-graph/735)

**Comment by nikku** [comment]
We do not plan to implement this feature request any time soon. Feel free to provide a PR.

Users can easily react to the `element.marker.update` events and update the actual SVG attributes (i.e. `fill`). Applying markers that way allows users to to export the change.

**Comment by zxiaozhou** [comment]
This is typically process instance rendering

> We do not plan to implement this feature request any time soon. Feel free to provide a PR.
> 
> Users can easily react to the `element.marker.update` events and update the actual SVG attributes (i.e. `fill`). Applying markers that way allows users to to export the change.

This is typically process instance rendering,But you can't get modeling( import NavigatedViewer from 'bpmn-js/lib/NavigatedViewer';)

**Comment by nikku** [comment]
@zxiaozhou Please do not [necrobumb](https://www.urbandictionary.com/define.php?term=necrobump) old issues, instead open a new qualified feature request describing what you need and why. Thank you!
