### ISSUE TITLE
Adjust scroll thresholds to avoid infinite scrolling

### ISSUE THREAD

**Issue by vkatushenok** [bpmn-io/diagram-js#169]
Auto-scroll should stop when mouse position outside of container border.

See [original post](https://forum.camunda.org/t/scrolling-is-broken-in-1-0/683).

**Solution**
Set defaults [here](https://github.com/bpmn-io/diagram-js/blob/568b06fe4205856ee7574fa5d0fd5ae555de3935/lib/features/auto-scroll/AutoScroll.js#L29) to all `0`.

**Comment by nikku** [comment]
Could you add a test case for the desired behavior?

**Comment by venkateshmech1990** [comment]
Kindly confirm how to restrict scroll within container area?
