### ISSUE TITLE
MoveShapeHandler.js assigns new position as a string 

### ISSUE THREAD

**Issue by Necr1s** [bpmn-io/diagram-js#188]
At Lines 46 - 50 of MoveShapeHandler.js:

>   assign(shape, {
>     parent: newParent,
>     x: shape.x + delta.x,
>     y: shape.y + delta.y
>   });

Resulting as NaN in the transformation matrix, when delta is negative and breaking the feature of moving a shape.

Example:
shape.x = 0125
delta.x = -71
x = "0125-71"

Possible solution:
Casting it to a number before the addition

> assign(shape, {
>     parent: newParent,
>     x: Number(shape.x) + Number(delta.x),
>     y: Number(shape.y) + Number(delta.y)
>   });

If accepted, this should also be adapted with the reverse operation at lines 94-98.

Issue on Crome Version 52.0.2743.116 m (64-bit)

**Comment by nikku** [comment]
I'd rather like to address the root cause of this issue than monkey patching the handler.

Why is `x` a string in the first place?

**Comment by Necr1s** [comment]
I am not sure where it set. I have a Diagram with:

> 	diagram = new Diagram
> 	({ 		
> 		canvas: 
> 		{
> 			container: document.getElementById('js-canvas')
> 		},
>         modules:
>         [
>          	require('./lib/draw'),
>          	require('diagram-js/lib/navigation/movecanvas'),
>          	require('diagram-js/lib/navigation/zoomscroll'),
>          	require('diagram-js/lib/command'),
>          	require('diagram-js/lib/features/modeling'),
>          	require('diagram-js/lib/features/rules'),
>          	require('diagram-js/lib/features/selection'),
>          	require('diagram-js/lib/features/interaction-events'),
>          	require('diagram-js/lib/features/dragging'),
>          	require('diagram-js/lib/features/resize'),
>          	require('diagram-js/lib/features/create'),
>          	require('diagram-js/lib/features/move')
>         ]
> 	});	

Where the module in lib/draw is my renderer, which draws the shape with: 

> paper.rect(offset, offset, width - offset * 2, height - offset * 2, r).attr(attributes);

Even if i cast these variables to numbers, it has the same behaviour.

The string value is in the element, when it es evaluated in `InteractionEvents.js` inside the `fire` method.
In the first call it is `x="0"`, because the element is at position zero. But in the second call  it is for example `x="0211"`. So maybe it happens at the save of the value, but I don't know where that is.

**Comment by Necr1s** [comment]
I found the origin of the String. It came from my metamodel, which was parsed from a file. I thought, that casting the numbers before calling `paper.rect` would be enough, but i have to cast them before calling the `handler(visuals, element, attributes)` method. I don't understand why I have to do that at that point, but I think this solved my problem. 
I would request a feature, that this becomes more robust to strings. A warning somewhere would also be nice :)

**Comment by nikku** [comment]
Why does that stuff come from your meta-model as a string rather than a number? I'd personally address that in one place (meta-model) or during import.

**Comment by Necr1s** [comment]
I am using the cmof-parser for parsing the model. But it could also be, that the numbers are casted to strings, during the transportation via socket.io.
