### ISSUE TITLE
Resize hitbox is not hit on click

### ISSUE THREAD

**Issue by Necr1s** [bpmn-io/diagram-js#189]
I am trying to resize a shape in my diagram and have loaded the resize module for it. The markers are shown on the corners of the selectionbox from the shape, but clicking them just drags the shape around. The modules for dragging and moving are also enabled.

The function `ResizeHandles.prototype.makeDraggable` is called, when the element is selected, but the function `startResize(event)` inside this function is never called. I think this is also the reason that the event `resize.start` is never emitted.

I guess that this could be a problem with the mouseclick event, that emits a click on the shape instead of the hitbox.
How do I tell him, that the hitbox has been hit and not the shape?

**Comment by philippfromme** [comment]
Hi,

did you specify a rule that makes your shape resizable? In [Resize.js](https://github.com/bpmn-io/diagram-js/blob/master/lib/features/resize/Resize.js#L120) you can see that there is a check for the shape being resizeable. If you want your shape to be resizable you have to provide a rule that enables that behaviour. You can see an example [here](https://github.com/bpmn-io/bpmn-js-examples/blob/master/custom-elements/app/custom-modeler/custom/CustomRules.js#L106). That may solve your problem.

**Comment by Necr1s** [comment]
Thanks for your answer, but the missing rule for the resize does not seem to be the problem. 

I think it starts more early. In the diagram-js.css file, the hitboxes have a entry `.djs-resizer-sw {
  cursor: nesw-resize;}`. This should make the cursor appear as a arrow, when it hovers the corner. But the cursor is not changed. The .css file seems to work though, because the cursor is changed on dragging.

**Comment by philippfromme** [comment]
Can you provide some more information? What shape are you trying to resize? A BPMN shape or a custom one? Which project are you using?

**Comment by Necr1s** [comment]
I am building my own Editor for custom diagrams and have implemented a custom renderer. I am using diagram-js as a base tool for the basic functions.

The instantiation of the diagram, where everything in .lib/ is implemented locally (basically copied and adapted from the bpmn modeler):

```
	diagram = new Diagram
	({ 		
		canvas: 
		{
			container: document.getElementById('js-canvas')
		},
        modules:
        [
         	require('./lib/draw'),
         	require('diagram-js/lib/navigation/movecanvas'),
         	require('diagram-js/lib/navigation/zoomscroll'),
         	require('diagram-js/lib/command'),
         	require('diagram-js/lib/features/modeling'),
         	require('diagram-js/lib/features/rules'),
         	require('./lib/features/rules'),
         	require('diagram-js/lib/features/selection'),
         	require('diagram-js/lib/features/interaction-events'),
         	require('diagram-js/lib/features/dragging'),
         	require('diagram-js/lib/features/resize'),
         	require('diagram-js/lib/features/create'),
         	require('diagram-js/lib/features/move'),
         	require('diagram-js/lib/features/attach-support'),
         	require('diagram-js/lib/features/label-support'),
         	require('./lib/features/label-editing'),
         	require('./lib/features/modeling/behavior')
        ]
	});	
```

Adding a shape to the canvas, where new_element is a parsed part of the metamodel:

```
	var shape = diagram.get('elementFactory').createShape(new_element);	
	diagram.get('create').start(event.originalEvent, shape);
```

The handler for a rectangle in my renderer:

```
 		'../app/lib/DD/DG.xmi:Rectangle': function(paper, element, attributes) 
 		{
 			var rect = drawRect(paper, element.width, element.height, element.cornerRadius , 0, attributes);
 			renderEmbeddedLabel(paper, element, element.labelAllign || 'center-middle');
 			return rect;
 		}
```

With:
```

   function drawRect(paper, width, height, r, offset, attributes) 
   {
 	  offset = offset || 0;	
	  return paper.rect(offset, offset, width - offset * 2, height - offset * 2, r).attr(attributes);
   }
```

**Comment by Necr1s** [comment]
I found the root of my problem. The page is divided with bootstrap into a menu and the canvas. After deleting the bootstrap part, everything worked as it should.

Interesting side fact: After loading the page, using the zoom and creating a new shape, the resize is working. If I first do anything else, the resize will not work.

I have not found a workaround for this for now, but since it is a problem with bootstrap, this issue can be closed.
