### ISSUE TITLE
npm version isn't up-to-date

### ISSUE THREAD

**Issue by samuelkitazume** [bpmn-io/diagram-js#190]
I'm trying to grunt build the bpmn-js project that's dependent of diagram-js.

But I always get this error:
```
Running "karma:single" (karma) task
25 08 2016 09:30:54.868:INFO [preprocessor.env]: Publishing variables:  []
25 08 2016 09:30:59.896:ERROR [framework.browserify]: bundle error
25 08 2016 09:30:59.896:ERROR [framework.browserify]: Error: Cannot find module
'diagram-js/lib/features/preview-support' from 'c:\repos\bpmn.io\lib\features\r
place-preview'
```

Checking out the commits I saw that preview-support is recently commited.

Maybe it's a problem of updating the npm version?

**Comment by nikku** [comment]
Did you checkout the hints on [how to build bpmn-js](https://github.com/bpmn-io/bpmn-js#building-the-project)?
