### ISSUE TITLE
Multi Label Support for Connections

### ISSUE THREAD

**Issue by KosrenDQ** [bpmn-io/diagram-js#202]
At the moment I just can add a single Label to a Connection. Comes from the model/index.js.
Multi Label Support would be nice, I want to create a UML Editor and there I need more Labels at a Association. 

However your library is pretty sweet.

**Comment by nikku** [comment]
We are happy to take a pull request on that feature request.

**Comment by nikku** [comment]
Addressed with #203.

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/diagram-js/commit/1b5fa55268137940ee7864294d255d309282677c.
