### ISSUE TITLE
Add 'copy' rule before copying

### ISSUE THREAD

**Issue by ricardomatias** [bpmn-io/diagram-js#204]
This allows an early return for elements that shouldn't be allowed to copy.

**Comment by nikku** [comment]
Is this related to our recent copy and paste changes? If so, is it still required?

**Comment by ricardomatias** [comment]
This is not required. This is just a suggestion, because there are certain scenarios where taking a look at which elements you want to copy, you can decide not to copy them. At the moment, we'll create the tree structure and while doing it, we're checking if it's allowed to copy them. So an early return makes sense if it's a big selection of elements, because it would be one of the first things to be done.

**Comment by nikku** [comment]
Ah, so like a global "Is it allowed to copy that selection thing"?

**Comment by ricardomatias** [comment]
Yes, so if you have an element in the selection which your sure it shouldn't be copied, it exits early. Would have to be a different rule like f.ex: 'selection.copy'.
