### ISSUE TITLE
Label is not being pasted

### ISSUE THREAD

**Issue by nikku** [bpmn-io/diagram-js#206]
`CopyPaste` currently copies labels but does not paste them due to [this line](https://github.com/bpmn-io/diagram-js/blob/master/lib/features/modeling/cmd/PasteHandler.js#L146).

__Expected__

* [ ] Copy paste pastes the label with the shape
* [ ] There exist test cases verifying the proper label copy and paste interaction

Broken test case attached via https://github.com/bpmn-io/diagram-js/commit/4d5c744d5aa2afc1613037fb089b66062bb466d3.

**Comment by KosrenDQ** [comment]
Hello I checked the problem. If you change Line 187 in the PasteHandler.js from:
label = labelTarget; 
to:
label = labelDescriptor;
Everything is fine and your tests runs.
I see that the created Element which will use as LabelTarget has not set the label itself. Therefore it is undefined by pasting and just the shape is pasted.
