### ISSUE TITLE
Emit overlay added / removed events

### ISSUE THREAD

**Issue by pedesen** [bpmn-io/diagram-js#209]
The overlays service should hook into the eventBus and should fire events whenever an overlay is being added or removed.

**Comment by vkatushenok** [comment]
I had put a quick fix for an interesting bug:
- comment on element
- delete element
- undo deletion - no comments appear in the bubble near the element
- comment on the element - you'll see another thread created with same reference, and targeting same element

**Comment by nikku** [comment]
What would be a use case for this?

**Comment by vkatushenok** [comment]
@nikku I think it was related to Cawemo commenting feature.

**Comment by nikku** [comment]
We'll not implement this feature without a proper use case.
