### ISSUE TITLE
what is the purpose of helper-svg 

### ISSUE THREAD

**Issue by mehrad-rafigh** [bpmn-io/diagram-js#215]
Hi everybody,

I am experiencing some issues with diagram-js@0.19.5
This version now adds a hidden, 0 x 0 svg node on the dom and this breaks my application. 

Can anyone on the bpmn-io team elaborate on why this svg node is being inserted? 

Is there a way I can opt out?

Cheers

**Comment by nikku** [comment]
We add the hidden element in order to be able to layout displayed text.

What kind of application do you build that is breaking because of this?
