### ISSUE TITLE
Pass parentIndex when creating connection

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/diagram-js#216]
When adding an element to the canvas you can pass parentIndex for ordering purposes. `CreateShapeHandler` and `CreateConnectionHandler` are responsible for adding the newly created element to the canvas but only `CreateShapeHandler` actually [passes on](https://github.com/bpmn-io/diagram-js/blob/master/lib/features/modeling/cmd/CreateShapeHandler.js#L59) `parentIndex`. `CreateConnectionHandler` [doesn't](https://github.com/bpmn-io/diagram-js/blob/master/lib/features/modeling/cmd/CreateConnectionHandler.js#L49). Therefore it is impossible to make ordering work properly for connections.

**Comment by nikku** [comment]
We should fix this, as it is clearly not the intended behavior.

I'll work on a PR.
