### ISSUE TITLE
Take z-index into account when creating Move Visuals

### ISSUE THREAD

**Issue by nikku** [bpmn-io/diagram-js#218]
Currently, our [`MovePreview` relies on connections always being on top of shapes](https://github.com/bpmn-io/diagram-js/blob/master/lib/features/move/MovePreview.js#L53). This assumption does not always hold true, depending on how you'd like to use the modeling tool (cf. https://github.com/bpmn-io/diagram-js/issues/216, https://github.com/bpmn-io/diagram-js/issues/213).

__Steps to Reproduce__

* Enforce connections to be always in the back, i.e. using an `OrderingProvider`
* Move shapes + connections
* __Connections are put in front of shape during the preview__

__Expected Behavior__

* [ ] Use existing `parent <-> child` hierarchy and properly render move preview according to that hierarchy.

**Comment by nikku** [comment]
Alternative is to simply use `ConnectionCropping` to fix this issue. May not even be worth investigating.

What do you thing @philippfromme?

**Comment by philippfromme** [comment]
Yeah, for that reason I introduced cropping which solves the issue. So it wouldn't actually be necessary to fix that but it would still be nice.

**Comment by nikku** [comment]
We accept PRs on this issue.
