### ISSUE TITLE
Check for existing originalEvent.target before using it, in the ToolManager

### ISSUE THREAD

**Issue by componentDidMount** [bpmn-io/diagram-js#219]
The selected line of code does not check if the originalEvent has a target nor if the target has a parentNode, it only checks if originalEvent has a value, but it can occur that originalEvent exists without having a target with a parentNode, then this throws and crashes diagram-js, because the line of code depends on originalEvent having a target and the target having a parentNode.

https://github.com/bpmn-io/diagram-js/blob/7dca989a1099260741152f6fbaa8fe5f865fa861/lib/features/tool-manager/ToolManager.js#L89

Besides on investigating why it has no target or a target without a parentNode, this line may only should execute after checking not just for originalEvent but also for originalEvent.target and originalEvent.target.parentNode.

QuickFix: add originalEvent.target to the if, so
```js
(originalEvent && originalEvent.target.parentNode.getAttribute('data-group') === 'tools')
```
becomes
```js
(originalEvent && originalEvent.target && originalEvent.target.parentNode && originalEvent.target.parentNode.getAttribute('data-group') === 'tools')
```
GoodFix: also investigate in which situations the target has no parentNode

Original error source: cawemo/kibana error _id: AVyhD6LjByp4hJH-opLe

**Comment by nikku** [comment]
Would be interesting to understand under which circumstances this happens.

Can you provide us with steps how to reproduce this issue (target environment, ...)?

**Comment by elgubenis** [comment]
I only know the userAgent for now, which is ```Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:52.0) Gecko/20100101 Firefox/52.0```, sadly i have no more hints yet it only occurred once until now.

**Comment by elgubenis** [comment]
It seems like the first method called which led to the error is here: https://github.com/bpmn-io/diagram-js/blob/efedec2045be2056b60d8fb2b2382b9692b9804b/lib/features/dragging/Dragging.js#L284
(got that from the stacktrace)

Not sure if that helps, but its all i got for now. So it seems like a MacOS Firefox 52 User wanted to drag and drop something and when the drag end event fired, the events target had no parentNode. (sorry, forgot the initial error message which is ```e.target.parentNode is null```)

**Comment by nikku** [comment]
Even with the description provided it will be impossible for us to track down this issue.

(We'd need a step by step guide to actually do this).

Closing this issue for now.
