### ISSUE TITLE
Don't rely on magic number for two column palette

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/diagram-js#223]
Currently the is layouted in two columns if the client height of its parent is less then 650px. Layouting should be smarter and take the number of entries in the palette into account since it can result in two column layouting of palettes with only a few entries.

<img width="94" alt="unbenannt" src="https://user-images.githubusercontent.com/7633572/28919219-d50f90dc-784c-11e7-8567-67172fbd29fc.PNG">

**Comment by nikku** [comment]
Agreed.

**Comment by nikku** [comment]
This is being addressed via https://github.com/bpmn-io/diagram-js/issues/199.

**Comment by nikku** [comment]
Fixed via #199
