### ISSUE TITLE
Keyboard handlers can't be overridden

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/diagram-js#226]
Since there is no way of prioritizing keyboard handlers I can't override a handler that was previously registered.

Use case: I built a token simulation plugin for bpmn-js that allows me to switch to simulation mode where I can't model. I can't reuse the 'l' key for toggling the log because it has already been assigned to toggling the lasso tool.

**Comment by nikku** [comment]
Makes sense. What about implementing a mode-aware keyboard that re-uses the existing one _or_ another one, based on the selected mode?

**Comment by philippfromme** [comment]
+1

**Comment by nikku** [comment]
We should add priorities (known from other event-based APIs in our system).

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/diagram-js/commit/4d72e386e2b734edc0fb2d77907b0e3ab6efead6
