### ISSUE TITLE
Make auto-hide of overlays optional

### ISSUE THREAD

**Issue by nikku** [bpmn-io/diagram-js#229]
Overlays should always show, independent of the diagram scale.

This is backed by the observation that people often get confused by the auto-hide functionality baked into this toolkit (like _Oh! Where did the overlays go?_ when zooming too far out of a diagram).

It should still be possible to revert back to the old behavior (making overlays disappear at < 0.7 scale).

__Tasks__

* [x] Make scaling optional
* [x] Allow setting own defaults for overlays

**Comment by vpanfilov** [comment]
Are you planning to add similar functionality to **tooltips** module later?

**Comment by nikku** [comment]
Not planned right now but would be nice to have some time. 

You can help us out with a pull request :wink:.

**Comment by vpanfilov** [comment]
@nikku, ok, maybe I will find some free time this month to rework **tooltips**.
