### ISSUE TITLE
EventBus overrides event context property 'type'.

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/diagram-js#231]
Using a property `type` when firing an event will result in the property being overridden by the event bus without warning.

```javascript
eventBus.on('foo', ({ type }) => {
  console.log(type); // 'foo' instead of 'bar'
});

eventBus.fire('foo', { type: 'bar' });
```

**Comment by nikku** [comment]
The rationale behind this is that components may inspect the `event` to understand what they are currently listening to:

```javascript
eventBus.on([ 'foo', 'bar' ], ({ type }) => {
  console.log(`caught event ${type}`);  
});
```

My suggestion is to not use `type` as a property. 

__Alternative Solutions__

* Pass eventType as a second argument into the closure:
   ```javascript
   eventBus.on('foo', ({ type }, eventType) => {
      console.log(`caught event ${eventType}`);  
      console.log(`context type ${type}`);
   });
   ```

**Comment by nikku** [comment]
The least thing we should do is emitting a warning, if the user passes a `type` property we're overriding.

**Comment by nikku** [comment]
> The least thing we should do is emitting a warning, if the user passes a `type` property we're overriding.

We'll do exactly this, some day maybe. Closing this issue for now, as we regard the `type` property as reserved (it's reserved on DOM level APIs, too).
