### ISSUE TITLE
Migrate to min-dash

### ISSUE THREAD

**Issue by nikku** [bpmn-io/diagram-js#234]
Right now we use [lodash](https://lodash.com/) as a utility library. Unfortunately, it has a massive footprint.

To give some stats right now the lodash helpers used in [bpmn-js](https://github.com/bpmn-io/bpmn-js) make up for `56K` (BPMN viewer) and `90K` (BPMN modeler) of the overall bundle size (unminified).

Even when minified, that amout of _utility_ is significant.

We can do better. [min-dash](https://github.com/bpmn-io/min-dash) provides us with all the utilities we need while being only `14K` in size and 4K minified. Plus, min-dash properly tree-shakes when using a current, ES2016 aware bundler (i.e. `webpack > 2`). 

__Tasks__

Migrate the following projects to min-dash:

* [x] bpmn-js
* [x] diagram-js
* [x] [bpmn-moddle](https://github.com/bpmn-io/bpmn-moddle/tree/min-dash)
* [x] [moddle](https://github.com/bpmn-io/moddle/tree/min-dash)
* [x] [moddle-xml](https://github.com/bpmn-io/moddle-xml/tree/min-dash)

**Comment by TheSharpieOne** [comment]
What is the remaining lift for this? I see progress seems to have stopped halfway through.
Just diagram-js and bpmn-js is left. Does min-dash contain all of the utilities needed for the migration or is there work to be identified and done on that front?

**Comment by nikku** [comment]
> I see progress seems to have stopped halfway through.

Well, bpmn-js and diagram-js are most of the work :wink:.

> Does min-dash contain all of the utilities needed for the migration or is there work to be identified and done on that front?

Most of the time there exists simple drop-in replacements in min-dash for the lodash utlities.

Three cases need special handling:

* similar to lodash@4 min-dash does not support the context (or _this_) parameter
* min-dash only contains `sortBy` and `uniqueBy` and not the more general unique properties we use in some places in the code base
* we use some obscure lodash functions in some places that we need to get rid of / replace by with simpler variants

**Comment by TheSharpieOne** [comment]
FWIW (and to prevent duplicate efforts), I'll take this on.

**Comment by nikku** [comment]
Great to hear you're giving it a try.

Please use the following style as a general pattern for requiring the utilities: 

```javascript
var forEach = require('min-dash').forEach,
    sortBy = require('min-dash').sortBy;
```

This makes later migration to ES6 easier and allows us to tree-shake (i.e. only include the utilities we actually need) during bundling.

**Comment by TheSharpieOne** [comment]
I created a bot to go through and make those changes. I am now going through those special cases. Some things like `sort` and `unique` do not exist in min-dash. `sortBy` and `uniqueBy` do exist. Would you accept a PR to add the generic methods (which would just call the "By" methods with a simple `(e) => e` extractor (currently the `toExtractor` does not handle an undefined `extractor` (it doesn't default to something like `(e) => e`, it just assumes a key/property value). I can open an issue there if you would like, or just inline an extractor (`(e) => e`) to each of the places where the "By" method is not used and make it use the "By" method.

**Comment by nikku** [comment]
`(e) => e` extractor won't work as min-dash uses a map under the hood to distinguish the different elements. Because of that it needs a object key (string / number) to use as an ID for the element.

**Comment by nikku** [comment]
As far as I am aware you cannot use Objects as keys in ES5, right?

**Comment by TheSharpieOne** [comment]
when doing `uniqueBy` and `sortBy` with a simple array, such as strings or numbers, you will need to provide an extractor, it would have to be `(e) => e` in order to work for those simple arrays.

**Comment by nikku** [comment]
I'd rather keep the min-dash API as it is and pass the identity extractor in these particular cases to make clear that `unique([ obj1, obj2, obj3 ])` won't work. 

Alternatively we'd need to detect potential miss-use and throw appropriate errors (which means higher complexity, larger bundle size, ...).

**Comment by nikku** [comment]
I've released new versions of the utilities with min-dash :copyright: inside.

**Comment by nikku** [comment]
Released a migrated diagram-js version.
