### ISSUE TITLE
Example renders incorrectly with firefox 57 (quantum)

### ISSUE THREAD

**Issue by faassen** [bpmn-io/diagram-js#243]
### Expected Behavior

The example in diagram-js behaves in Firefox 57 like in Chrome.

### Actual Behavior

* The palette doesn't display the icons, nor do they work (the minimization feature at the bottom does work). 

* No remove or connect icons appear when you click on a box, nor do they work.

![diagramjs](https://user-images.githubusercontent.com/327472/34726545-9b7bb3ac-f554-11e7-98a0-1d4e1cbf804b.png)

### Steps to reproduce the Behavior

Run the example in ``diagram-js/example`` using grunt auto-build. Things work as expected in Chrome, but not in Firefox.

**Comment by nikku** [comment]
Any errors you see in the developer console?

**Comment by nikku** [comment]
Checkout the `index.html` in the example. Firefox quantum does not seem to recognize the embedded SVG styles anymore. Other than that, the demo works as it should.

**Comment by faassen** [comment]
Odd that it doesn't work with embedded SVG styles. I can't find any obvious reason why it's not working. Would it make sense to refactor the example so that it includes SVGs differently?

**Comment by nikku** [comment]
> Would it make sense to refactor the example so that it includes SVGs differently?

We accept PRs on this.

**Comment by nikku** [comment]
This should be addressed via https://github.com/bpmn-io/diagram-js/commit/6121f35717d6547644fa9594981124e44d53b435.
