### ISSUE TITLE
InteractionEvents throws errors when hovering elements // Missing handler for event 'element.mousemove'

### ISSUE THREAD

**Issue by StrohMax** [bpmn-io/diagram-js#245]
### Expected Behavior
- No errors are thrown

### Actual Behavior
- Every time you hover over an element, the console throws an error
- The first time you hover over a connection, it stops throwing errors

### Steps to reproduce the Behavior
My environment: diagram-js v0.28.0 and bpmn-js v0.26.6, tested in Firefox v58 and IE11

1. Create a Modeler-Object
2. Load a diagram into the modeler
3. Hover over any diagram elements except connections
4. While hovering look into the console of the browser
5. Hover over a connection
6. Look at the console

### Possible Solution
I'm not into your project, but digged a bit into your code to find the source of the error. Here's what I found out and what I did to fix this issue, but I'm not sure whether you just forgot to add an event to the bindings object or whether you actively didn't include it with a good reason. But this worked for me:

Inside of the diagram-js Lib, there's a module that is responsible for InteractionEvents (InteractionEvents.js). I found out, that the error appears, when this module tries to unbind the eventhandler for the event "element.mousemove", because the handler doesn't exist until you hover over a connection. While unbinding you call mouseHandler(localEvent).$delegate. I digged into the mouseHandler(localEventName)-function and found out, that the object 'handlers' also doesn't contain a handler for the element.mousemove-event. Because of that, the mouseHandler-function returns undefined and inside the unregisterEvent-function, JavaScript throws an error because you're calling .$delegate of undefined. For more details look at the screenshot I will append.

I fixed this issue with adding the 'element.mousemove'-event to the bindings object, but I'm not sure whether it maybe had reasons to not add this event at this point.

I hope this will help to fix or find the bug!

Code Injections:
function unregisterEvent(node, event, localEvent) {
    console.log('===== inside unregister Event function =====');
    console.dir('calling mouseHandler(' + localEvent + ')...');
    domDelegate.unbind(node, event, mouseHandler(localEvent).$delegate);
  }

function mouseHandler(localEventName) {
    console.log('=== inside mouseHandler-function ===');
    console.log('localEventName:');
    console.dir(localEventName);
    console.log('handlers object:');
    console.dir(handlers);
    console.log('The handler for the event "element.mousemove" is not part of the handlers object.' +
        'Adding the event to the bindings object doesn\'t throw these errors! Did you maybe forgot to add it to the bindings object?');
    return handlers[localEventName];
  }

My hotfix:
var bindings = {
    mouseover: 'element.hover',
    mouseout: 'element.out',
    click: 'element.click',
    dblclick: 'element.dblclick',
    mousedown: 'element.mousedown',
    mouseup: 'element.mouseup',
    mousemove: 'element.mousemove', // <--- ADDED THIS EVENT
    contextmenu: 'element.contextmenu'
  };

Thrown errors:
![errors-unhandled-event_diagram-js_interactionevents](https://user-images.githubusercontent.com/29775599/35735998-dbd16d86-0826-11e8-87c0-3a09b8df745a.PNG)

**Comment by nikku** [comment]
Released `diagram-js@0.28.1` with the fix.
