### ISSUE TITLE
Creating an additional PopupMenuProvider should not overwrite ReplaceMenu entries

### ISSUE THREAD

**Issue by pedesen** [bpmn-io/diagram-js#253]
### Expected Behavior

I would expect it to be possible to register an additional PopupMenuProvider. The registered popup menu should open on click on a custom context pad entry. I would expect that this does not interfere with the replace menu (which is also a PopupMenuProvider).

### Actual Behavior

On ContextPad open:
* the ReplaceMenu entries get created first and stored in `_current.entries` and `_current.headerEntries`
* the additional PopupMenu entries are created second, overwriting `_current.entries` and `_current.headerEntries`

On ReplaceMenu open:
*  the PopupMenu opens with the (wrong) entries of the additional PopupMenu

### Steps to reproduce the Behavior

* create a PopupMenuProvider and register it in PopupMenu
* click on element
* open context pad
* open replace menu 
* the replace menu opens with the wrong content

### Proposed solution

The lifecycle of the `_current` object in `PopupMenu` needs to change in order to achieve this. Ideally the current popup menu entries are created when opening the popup menu, and not already when opening the context pad. It probably makes sense to merge `PopupMenu.create` into`PopupMenu.open` and then only call it on a click on the respective context pad entry. This would imply a breaking change in `PopupMenu`.

**Comment by SanderBreivik** [comment]
Is it possible to allow it to actually overwrite entries? I want to have total control of which ReplaceOptions to offer @philippfromme
