### ISSUE TITLE
Example app not rendering the palette

### ISSUE THREAD

**Issue by cshen4** [bpmn-io/diagram-js#262]
### Expected Behavior
the screenshot in the example app documentation

### Actual Behavior
![image](https://user-images.githubusercontent.com/16641040/41355908-86229e7e-6ef0-11e8-8cec-15e225a7abf0.png)

### Steps to reproduce the Behavior
Followed all the instructions in the docs. Note: my npm version is 5.6.0, node version is 9.11.1

**Comment by cshen4** [comment]
i first ran `npm install` inside the example directory, then ran  `npm run dev` from the example directory

**Comment by nikku** [comment]
Please verify whether it runs against the latest master.

**Comment by cshen4** [comment]
![image](https://user-images.githubusercontent.com/16641040/41432232-593343f2-6fe3-11e8-9f87-27a84945c6ba.png)
i just pulled the most recent changes and this is what the latest example app looks like

I also did `npm install` in the main directory and ran `npm run build`and got ```PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 1109 of 1112 (skipped 3) SUCCESS (16.854 secs / 10.606 secs)
TOTAL: 1109 SUCCESS```
