### ISSUE TITLE
CommandHandler.js | Incorrect Documentation For preExecute  Function 

### ISSUE THREAD

**Issue by ChaitanyaBabar** [bpmn-io/diagram-js#263]
### Expected Behavior
The documentation/comment for  `CommandHandler.prototype.preExecute = function(context) {};`  must be  
/**
  Execute actions **_before_** the actual command execution but
 grouped together (for undo/redo) with the action.
 
  @param {Object} context the execution context
 */

### Actual Behavior
Current documentation is 
/**
    Execute actions **_after_** the actual command execution but
    grouped together (for undo/redo) with the action.
 
   @param {Object} context the execution context
 */

### Steps to reproduce the Behavior
Go to the Source code for CommandHandler [here](https://github.com/bpmn-io/diagram-js/blob/master/lib/command/CommandHandler.js).

**Comment by nikku** [comment]
Thanks for the fix.
