### ISSUE TITLE
Click edge (sequence flow) error

### ISSUE THREAD

**Issue by skycodeviper** [bpmn-io/diagram-js#265]
### Expected Behavior
Normally click will trigger a pop-up menu.

### Actual Behavior
I've just upgrade versions to their latest : 

```
"bpmn-js": "2.3.0",
"bpmn-js-properties-panel": "0.25.2",
"diagram-js": "2.4.0",
"diagram-js-direct-editing": "1.3.0",
```

When I click on the edge between tasks, error occurred like this:

```
EventBus.js:382 TypeError: Failed to execute 'setTranslate' on 'SVGTransform': The provided float value is non-finite.
    at transform (SvgTransformUtil.js:16)
    at ResizeHandles._createResizer (ResizeHandles.js:126)
    at ResizeHandles.createResizer (ResizeHandles.js:137)
    at ResizeHandles.addResizer (ResizeHandles.js:163)
    at forEach (index.esm.js:162)
    at ResizeHandles.js:60
    at invokeFunction (EventBus.js:466)
    at EventBus._invokeListener (EventBus.js:367)
    at EventBus._invokeListeners (EventBus.js:355)
    at EventBus.fire (EventBus.js:315)
EventBus._invokeListener @ EventBus.js:382
EventBus._invokeListeners @ EventBus.js:355
EventBus.fire @ EventBus.js:315
Selection.select @ Selection.js:94
(anonymous) @ SelectionBehavior.js:74
invokeFunction @ EventBus.js:466
EventBus._invokeListener @ EventBus.js:367
EventBus._invokeListeners @ EventBus.js:355
EventBus.fire @ EventBus.js:315
fire @ InteractionEvents.js:84
triggerMouseEvent @ InteractionEvents.js:147
(anonymous) @ Bendpoints.js:93
```

### Steps to reproduce the Behavior
Just click the edge

**Comment by nikku** [comment]
From which version did you upgrade?
What is the input that triggers the above error?

**Comment by skycodeviper** [comment]
Thanks for replying ! I upgraded from : 
    "bpmn-js": "^0.20.5",
    "bpmn-js-properties-panel": "^0.13.1",
    "diagram-js": "0.19.3"

I think it's big change as many functions definitions are changed when there is newer version. However, I can still make some functionalities work as the older version, some not. One of them currently blocking the upgrade is this edge click issue. 

When normally created a process, some tasks and edges, by clicking any edge, it showed me the previous error stack trace. However, clicking on any task vertex it does not trigger this error. 

The same error shows before and after trying different versions of digram-js, a working version was found (0.19.3), now I'm considering trying different versions again to see if it can work. But since I updated most of bpmn js libs, I lost clues what could be the real change that lead to this problem. Also if possible I want to get your suggestion about a good version combinations of these component so that I can try starting from the suggested versions.  

Also I appreciate if you can point out any possible change or reason that may lead to this problem. Thanks!

**Comment by nikku** [comment]
I'd suggest you to upgrade to the latest `^0.x` versions of diagram-js and bpmn-js.

I'd further suggest you to debug the matter and figure out where the error message:

```
Failed to execute 'setTranslate' on 'SVGTransform': The provided float value is non-finite.
```

originates, i.e. where the non-finite float value is coming from.

**Comment by xuchaojavascript** [comment]
I also met the same problem. Has this problem been solved?

**Comment by xuchaojavascript** [comment]
Recently, I also encountered this problem. The reason for my mistake is that in bpmn, there is a control that can be changed in size. When we add this control, we can add some rules to restrict the use of the control for certain types of elements, while edge (sequence flow) can not be zoomed in or out. Therefore, we need to zoom in and out the edge restriction. In the case of bpmn, the developer gave several legends, in which any control over the size was added, the error would be reported when the edge was clicked. I Ying

**Comment by lucianodltec** [comment]
Hi guys, I'm experiecing this issue, could the opsolve change me merged into diagram-js?

Current running below versions:
"diagram-js": "^7.0.0",
"bpmn-js": "^8.1.0"

Thanks in advance.

**Comment by nikku** [comment]
Please do not [necrobump](https://www.urbandictionary.com/define.php?term=necrobump) old issues.

Instead, create a new issue using one of our existing issue templates. This issue specifically was closed as _cannot reproduce_. For a new issue to be actionable for us we need concrete steps to reproduce your case.
