### ISSUE TITLE
example app not working

### ISSUE THREAD

**Issue by darkworks** [bpmn-io/diagram-js#267]
i download diagram js extracted and try to run example , but it wont run , missing css/diagram-js.css and 
Uncaught SyntaxError: Unexpected identifier in app.js

### Expected Behavior
Example should work

### Actual Behavior
missing css file and have error in app.js

### Steps to reproduce the Behavior
download diagram js and try to run example app

**Comment by nikku** [comment]
How do you attempt to run the example?

**Comment by darkworks** [comment]
i run the index.html in app folder , the missing css/diagram-js.css file i found in assets folder now its just that error in app.js 

Uncaught SyntaxError: Unexpected identifier in app.js

**Comment by nikku** [comment]
Please follow the [Building the app](https://github.com/bpmn-io/diagram-js/tree/master/example#building-the-project) hints to build and run the example.

**Comment by darkworks** [comment]
ya now working
