### ISSUE TITLE
How to use diagram js in AMD project

### ISSUE THREAD

**Issue by Priya-Ahuja** [bpmn-io/diagram-js#275]
I have been trying adding diagram.js as node module in my AMD project using npm i diagram js, but when i tried to bundle it as its given in documentation and use the bundle file in project like 

define(['diagram',function(diagram){console.log(diagram)}]);  **diagram is coming as undefined.**
Is bundle correct ? Attached is the bundle file

[bundle.zip](https://github.com/bpmn-io/diagram-js/files/2370369/bundle.zip)

@nikku please guide

**Comment by nikku** [comment]
Please provide additional details on:

* your project setup
* how you bundle the application
* how you consume it

Make sure you produce a standalone [UMD](https://github.com/umdjs/umd) bundle. How to do that depends on the browser you're using.
