### ISSUE TITLE
EventBus _invokeListeners mutates list of listeners during for loop

### ISSUE THREAD

**Issue by nickeeex** [bpmn-io/diagram-js#293]
__Describe the Bug__

EventBus _invokeListeners mutates list of listeners during for loop causing listeners not get executed.

__Steps to Reproduce__

We have a custom listener on commandStack.changed with a priority of 0.
One of the listeners for the event has a wrappedCallback that calls removeListener on itself.
The wrappedCallback listener is added when the replacement popup menu is opened here is the stack:
![image](https://user-images.githubusercontent.com/6636662/47565222-7470b080-d930-11e8-806e-7d3902ab76e9.png)

This removes a item from the list of listeners making the last listener not getting called at all.

![eventbusbug](https://user-images.githubusercontent.com/6636662/47564444-b9471800-d92d-11e8-90e2-e7db7e9ff6d2.gif)

__Expected Behavior__

The last listener should still be executed.

__Workaround__

Add priority on custom event so it is not last.

__Environment__

Please complete the following information:

 - diagram-js 2.5.1

**Comment by nikku** [comment]
Thanks for your bug report.

Could you provide a [test case](https://github.com/bpmn-io/diagram-js/blob/master/test/spec/core/EventBusSpec.js) that defines your desired behavior?

**Comment by nickeeex** [comment]
it('should call all listeners atleast once', function() {
      // given
      var listener = sinon.spy();
      var listener2 = sinon.spy();

      eventBus.once('event', listener);
      eventBus.on('event', listener2);

      // when
      eventBus.fire('event');

      // then
      expect(listener).to.have.been.calledOnce;
      expect(listener2).to.have.been.calledOnce; // this fails currently
    });

**Comment by nikku** [comment]
Are you interested in contributing a fix for this issue?

**Comment by nickeeex** [comment]
I can probably make a small pr for this on Monday.

**Comment by nikku** [comment]
Not as easy to fix as indicated in [this comment](https://github.com/bpmn-io/diagram-js/pull/296#issuecomment-440183159).

**Comment by nikku** [comment]
Added additional test cases via https://github.com/bpmn-io/diagram-js/commit/dedecaaf9fbf4e03a4d7288300ef0196e7e8dd0e.

**Comment by nikku** [comment]
In which exact scenario did you come across this issue? Maybe we can provide you with a workaround until this bug is fixed.

**Comment by nickeeex** [comment]
> In which exact scenario did you come across this issue? Maybe we can provide you with a workaround until this bug is fixed.

Oh, the workaround was simple, just changed priorities to get our own event to get processed before the internal one. :)

Just reported it to make the issue known.

**Comment by nikku** [comment]
That is good to hear.

As indicated in the PR a solution to this bug may not be easily found, especially as the EventBus is a performance critical part of the toolkit. I'll keep investigating, cannot promise a quick fix for this one though.

**Comment by nikku** [comment]
Will be fixed via https://github.com/bpmn-io/diagram-js/pull/308.

**Comment by barmac** [comment]
Closed via #308.
