### ISSUE TITLE
Context pad deferring when adding flow elements (since version 3.x)

### ISSUE THREAD

**Issue by StrohMax** [bpmn-io/diagram-js#310]
__Describe the Bug__

Hi guys. Since version 3.x of diagram-js we are expierencing weird positioning bugs with the context pad. After adding an flowelement and re-selecting any element of the diagram, the context pad begins to defer to the left. When adding more elements the effect is even getting bigger. I made a gif to show even better what the problem is. Because the positions of the context pads are calculated by js code and not by css rules, we have no idea where the error comes from. Unfortunately the error does not occur on the demo page (https://demo.bpmn.io/), so we know you may not be able to reproduce the error, but we hope, that you have an idea where the problem could come from.

I also attach a screenshot of an example case, where the css "left"-property was calculated and set to a wrong value.

![diagram-js-3_context-pad-positioning](https://user-images.githubusercontent.com/29775599/53171774-f5d90680-35e3-11e9-8722-07ca5ddd60d7.gif)
![deferred-context-pad_wrong-position](https://user-images.githubusercontent.com/29775599/53171784-fb365100-35e3-11e9-93aa-41c8470ed88a.PNG)

__Steps to Reproduce__

1. Open a project with bpmn-js & diagram-js above version 3.x
2. Click on an existing element (e.g. a task) => context pad opens
3. Click in context pad on task-icon to auto-create a new task => context pad opens at the new element
4. Deselect the new element
5. Select the new element again => context pad has deferred to the left
6. Repeat steps 2 to 5 => context pad deferres even more and more
7. Same behaviour if element is created with djs-palette

__Expected Behavior__

The context pad always opens right-aligned to the selected element

__Environment__

 - Browser: Firefox 65.0.1, Chrome 72.0.3626.109
 - OS: Windows 7
 - Library version: 3.1.3 (bug appears since bpmn-js & diagram-js 3.0.x versions)

**Comment by StrohMax** [comment]
Sorry - selected the wrong element on the screenshot. This is the correct element:

![deferred-context-pad_wrong-position](https://user-images.githubusercontent.com/29775599/53172057-ae9f4580-35e4-11e9-902c-094af92bc55b.PNG)

**Comment by nikku** [comment]
Could you confirm that it still works in [diagram-js@2.6.1](https://github.com/bpmn-io/diagram-js/blob/master/CHANGELOG.md#261)?

**Comment by nikku** [comment]
Complete list of changes we applied in v3.0.0: https://github.com/bpmn-io/diagram-js/compare/v2.6.1...v3.0.0

Regarding the context pad specifically we added the ability to scale it (cf. https://github.com/bpmn-io/diagram-js/compare/v2.6.1...v3.0.0#diff-abac683ae00c5bd1cb0e85092cc8aaaa).

Maybe that helps you to dig into the issue. It seems like you guys customize the BPMN modeler instance. Remove it and check, if the issue persists.

It may also be worth having a look into the [breaking changes](https://github.com/bpmn-io/diagram-js/blob/master/CHANGELOG.md#300) introduced in v3.0.0.

**Comment by StrohMax** [comment]
> 
> 
> Could you confirm that it still works in [diagram-js@2.6.1](https://github.com/bpmn-io/diagram-js/blob/master/CHANGELOG.md#261)?

Yes! v2.6.1 is what we are using in our productive version! There everything works

**Comment by StrohMax** [comment]
Thanks for the fast replay and the good intuition: You were right! We modified the embedded comments module, which accidently pushed **all** overlays to the left (including the context pad). So we produced the error by ourselves haha

Nevertheless thanks a lot, you helped us findeing the error very quick!

**Comment by nikku** [comment]
Best errors: Not our errors. :wink:
