### ISSUE TITLE
Cannot run the example application

### ISSUE THREAD

**Issue by nidafarooqui** [bpmn-io/diagram-js#311]
I cloned the repo and ran `npm install` then ran `npm run dev`. 

However, I cannot run the example application at all. I have tried
both `npm run all` and `npm run dev` and I get this shown on my console:

                                                                                                                                                               
    karma start "--auto-watch" "--no-single-run"

    (node:21024) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    i ｢wdm｣: Hash: 3879665b411e2fff46cc
    Version: webpack 4.26.1
    Time: 11271ms
    Built at: 02/25/2019 4:18:58 PM
    i ｢wdm｣: Compiled successfully.
    i ｢wdm｣: Compiling...
    i ｢wdm｣: Hash: 95793c456667c868a590
    Version: webpack 4.26.1
    Time: 13013ms
    Built at: 02/25/2019 4:19:00 PM
        Asset      Size      Chunks             Chunk Names
    test\suite.js  2.28 MiB  test\suite  [emitted]  test\suite
    Entrypoint test\suite = test\suite.js
    [./test sync recursive Spec\.js$] ./test sync Spec\.js$ 4.55 KiB {test\suite} [built]
    [./test/matchers/BoundsMatchersSpec.js] 1.51 KiB {test\suite} [optional] [built]
    [./test/matchers/ConnectionMatchersSpec.js] 2.12 KiB {test\suite} [optional] [built]
    [./test/spec/DiagramSpec.js] 2.53 KiB {test\suite} [optional] [built]
    [./test/spec/command/CommandInterceptorSpec.js] 13.9 KiB {test\suite} [optional] [built]
    [./test/spec/command/CommandStackSpec.js] 19.9 KiB {test\suite} [optional] [built]
    [./test/spec/core/CanvasSpec.js] 44.9 KiB {test\suite} [optional] [built]
    [./test/spec/core/ElementRegistrySpec.js] 4.98 KiB {test\suite} [optional] [built]
    [./test/spec/core/EventBusSpec.js] 19.3 KiB {test\suite} [optional] [built]
    [./test/spec/core/GraphicsFactorySpec.js] 814 bytes {test\suite} [optional] [built]
    [./test/spec/draw/DefaultRendererSpec.js] 2.25 KiB {test\suite} [optional] [built]
    [./test/spec/draw/StylesSpec.js] 792 bytes {test\suite} [optional] [built]
    [./test/spec/environment/MockingSpec.js] 731 bytes {test\suite} [optional] [built]
    [./test/spec/features/align-elements/AlignElementsSpec.js] 4.24 KiB {test\suite} [optional] [built]
    [./test/suite.js] 93 bytes {test\suite} [built]
    + 322 hidden modules
    i ｢wdm｣: Compiled successfully.
    25 02 2019 16:19:01.023:WARN [karma]: No captured browser, open http://localhost:9876/
    25 02 2019 16:19:01.035:INFO [karma-server]: Karma v3.1.1 server started at http://0.0.0.0:9876/
    25 02 2019 16:19:01.036:INFO [launcher]: Launching browsers PhantomJS with concurrency unlimited
    25 02 2019 16:19:01.072:INFO [launcher]: Starting browser PhantomJS
    25 02 2019 16:19:05.337:INFO [PhantomJS 2.1.1 (Windows 8 0.0.0)]: Connected on socket ot1- 
    YWC6a02K-H55AAAA with id 32074209
    ERROR: 'unhandled error in event listener'
    ERROR: 'failingListener
    invokeFunction
    _invokeListener
    _invokeListeners
    fire

    assertThrows@http://localhost:9876/base/node_modules/chai/chai.js? 
    db92883971379fbea71a12c25b271c26a3afc3f6:2991:10
    methodWrapper@http://localhost:9876/base/node_modules/chai/chai.js? 
    db92883971379fbea71a12c25b271c26a3afc3f6:7824:30

    callFn@http://localhost:9876/base/node_modules/mocha/mocha.js? 
    840d4fbbcc65a16cec39f9e25af2ea6d2cff68ea:4550:25
    run@http://localhost:9876/base/node_modules/mocha/mocha.js? 
    840d4fbbcc65a16cec39f9e25af2ea6d2cff68ea:4542:13
    runTest@http://localhost:9876/base/node_modules/mocha/mocha.js? 
    840d4fbbcc65a16cec39f9e25af2ea6d2cff68ea:5078:13
    http://localhost:9876/base/node_modules/mocha/mocha.js? 
    840d4fbbcc65a16cec39f9e25af2ea6d2cff68ea:5196:19
    next@http://localhost:9876/base/node_modules/mocha/mocha.js? 
    840d4fbbcc65a16cec39f9e25af2ea6d2cff68ea:4992:16
    http://localhost:9876/base/node_modules/mocha/mocha.js? 
    840d4fbbcc65a16cec39f9e25af2ea6d2cff68ea:5002:11
    next@http://localhost:9876/base/node_modules/mocha/mocha.js? 
    840d4fbbcc65a16cec39f9e25af2ea6d2cff68ea:4926:16
    http://localhost:9876/base/node_modules/mocha/mocha.js? 
    840d4fbbcc65a16cec39f9e25af2ea6d2cff68ea:4970:9
    timeslice@http://localhost:9876/base/node_modules/mocha/mocha.js? 
    840d4fbbcc65a16cec39f9e25af2ea6d2cff68ea:82:27'
    ERROR: 'unhandled error in event listener'
    ERROR: 'failingListener
    invokeFunction
    _invokeListener
    _invokeListeners
    fire

    assertThrows@http://localhost:9876/base/node_modules/chai/chai.js? 
    db92883971379fbea71a12c25b271c26a3afc3f6:2991:10
    methodWrapper@http://localhost:9876/base/node_modules/chai/chai.js? 
    db92883971379fbea71a12c25b271c26a3afc3f6:7824:30

    callFn@http://localhost:9876/base/node_modules/mocha/mocha.js? 
    840d4fbbcc65a16cec39f9e25af2ea6d2cff68ea:4550:25
    run@http://localhost:9876/base/node_modules/mocha/mocha.js? 
    840d4fbbcc65a16cec39f9e25af2ea6d2cff68ea:4542:13
    runTest@http://localhost:9876/base/node_modules/mocha/mocha.js? 
    840d4fbbcc65a16cec39f9e25af2ea6d2cff68ea:5078:13
    http://localhost:9876/base/node_modules/mocha/mocha.js? 
    840d4fbbcc65a16cec39f9e25af2ea6d2cff68ea:5196:19
    next@http://localhost:9876/base/node_modules/mocha/mocha.js? 
    840d4fbbcc65a16cec39f9e25af2ea6d2cff68ea:4992:16
    http://localhost:9876/base/node_modules/mocha/mocha.js? 
    840d4fbbcc65a16cec39f9e25af2ea6d2cff68ea:5002:11
    next@http://localhost:9876/base/node_modules/mocha/mocha.js? 
    840d4fbbcc65a16cec39f9e25af2ea6d2cff68ea:4926:16
    http://localhost:9876/base/node_modules/mocha/mocha.js? 
    840d4fbbcc65a16cec39f9e25af2ea6d2cff68ea:4970:9
    timeslice@http://localhost:9876/base/node_modules/mocha/mocha.js? 
    840d4fbbcc65a16cec39f9e25af2ea6d2cff68ea:82:27'
    PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 1238 of 1241 (skipped 3) SUCCESS (11.684 secs / 6.463 
    secs)
    TOTAL: 1238 SUCCESSS

I was expecting some way to see the app running on **http://localhost:9876/** but instead I saw this:

![diagram-js](https://user-images.githubusercontent.com/8697408/53334491-d5c68180-391a-11e9-8456-9065d340f45d.PNG)
![diagram-js-2](https://user-images.githubusercontent.com/8697408/53334493-d7904500-391a-11e9-8eb6-0fceaccc9557.PNG)

Also running npm audit showed this:
````

 === npm audit security report ===

##### Run  npm install --save-dev karma@4.0.0  to resolve 1 vulnerability
SEMVER WARNING: Recommended action is a potentially breaking change

  Low             Regular Expression Denial of Service

  Package         braces

  Dependency of   karma [dev]

  Path            karma > expand-braces > braces

  More info       https://nodesecurity.io/advisories/786



##### Run  npm update handlebars --depth 3  to resolve 1 vulnerability

  High            Prototype Pollution

  Package         handlebars

  Dependency of   karma-coverage [dev]

  Path            karma-coverage > istanbul > handlebars

  More info       https://nodesecurity.io/advisories/755



found 2 vulnerabilities (1 low, 1 high) in 7643 scanned packages
  run `npm audit fix` to fix 1 of them.
  1 vulnerability requires semver-major dependency updates.

````

 - Browser: Google Chrome Version 72.0.3626.119
 - OS: Windows 10
 - node version v10.9.0

**Comment by nikku** [comment]
`npm run dev` in the project root does not start the example application but runs our comprehensive test suite instead (as you documented very well in your post).

I suggest you to jump into the `example` directory and `npm run dev` there.

```
cd example
npm install
npm run dev
```
