### ISSUE TITLE
EventBus.on throws when callback is an async function or generator

### ISSUE THREAD

**Issue by xcrzx** [bpmn-io/diagram-js#329]
__Describe the Bug__

Due to the bug in `min-dash` (https://github.com/bpmn-io/min-dash/issues/10) when an async function is passed as the second argument to EventBus.prototype.on (https://github.com/bpmn-io/diagram-js/blob/master/lib/core/EventBus.js#L124) it throws `new Error('priority must be a number')`. 

__Steps to Reproduce__

```js
eventBus.on('foo', async function() {});
```
Throws: `Error: Uncaught [Error: priority must be a number]`

__Expected Behavior__

It doesn't throw.

__Environment__

Please complete the following information:

 - Browser: Chrome 74
 - OS: OS X
 - Library version: 3.3.0

**Comment by barmac** [comment]
This will be fixed with next min-dash release and update.
