### ISSUE TITLE
npm release does not match example code

### ISSUE THREAD

**Issue by nigel-daniels** [bpmn-io/diagram-js#331]
Hi, 

I am just getting started with diagram-js and tried to recreate the example in my own app with diagram-js as a dependency using npm. Unfortunately the example and npm version are out of step.

**Situation**
Example code throws an error on select as the method isFrameElement is missing from the Elements in the utils directory.

**Reproduction**

1. Create an app and install diagram-js using npm.
2. Attempt to load the diagram page.
3. The load fails on execution of the selection.

**Expectation**
The expectation is that the diagram functions exactly like the standalone example does.

**Environment**

Please complete the following information:

 - Browser: Safari 12.1
 - OS: macOS 10.14.4
 - Library version: 3.3.0

**Suggested Fix**
Push a new release so the example works against the npm version.

**Comment by philippfromme** [comment]
You're right we have updated the example to include frame elements but haven't released a new version, yet. We could either move the example to a separate repository as we've done with the [bpmn-js examples](https://github.com/bpmn-io/bpmn-js-examples) or keep the updated example on a branch until we've released a new version.

I've created an issue suggesting the former: https://github.com/bpmn-io/diagram-js/issues/332

In the meantime, if you need frame elements you could `npm link` this repository locally. If you don't need them you can remove the respective code.

**Comment by nikku** [comment]
Consider checking out a released branch of the project (with the example in it) and you're fine, too :postal_horn:.
