### ISSUE TITLE
Integrate Connection Preview With Preview Support

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/diagram-js#334]
We should integrate the recently created [ConnectPreview](https://github.com/bpmn-io/diagram-js/blob/master/lib/features/connect/ConnectPreview.js) and [CreateConnectPreview](https://github.com/bpmn-io/diagram-js/blob/master/lib/features/create/CreateConnectPreview.js) with our existing [PreviewSupport](https://github.com/bpmn-io/diagram-js/blob/master/lib/features/preview-support/PreviewSupport.js) therefore also ensuring that markers will be colored properly.

**Comment by nikku** [comment]
Invalid.
