### ISSUE TITLE
Center Grid around Viewbox on Viewbox Changed

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/diagram-js#339]
Currently, the grid is always centered around 0, 0 and never updated. If a user scrolls the canvas too far he will see no grid anymore. To prevent that the grid should always be centered around the viewbox after the viewbox changed.

**Comment by nikku** [comment]
In case we merge https://github.com/bpmn-io/diagram-js/pull/361, should we close this issue?

**Comment by barmac** [comment]
Closed via https://github.com/bpmn-io/diagram-js/pull/340#pullrequestreview-249749224
