### ISSUE TITLE
Error running tests

### ISSUE THREAD

**Issue by yfwz100** [bpmn-io/diagram-js#378]
__Describe the Bug__

When `npm run dev` is executed , the following error is reported:

```
04 07 2019 09:44:51.891:ERROR [plugin]: Error during loading "D:\study-workspace\bpmn\diagram-js\node_modules/karma-phantomjs-launcher" plugin:
  The "path" argument must be of type string. Received type object
(node:23180) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
```

__Steps to Reproduce__

1. run `npm i` to fetch dependencies
2. run `npm run dev`

__Expected Behavior__

Run the development build.

__Environment__

 - OS: Windows 10
 - Library version: 4.0.0

**Comment by nikku** [comment]
@philippfromme Could you check, whether you can reproduce the issue?

**Comment by philippfromme** [comment]
Sure.

**Comment by philippfromme** [comment]
I cannot reproduce this issue on my machine. OS: Windows 10

**Comment by yfwz100** [comment]
I got it... Installing phantomjs needs post-script. I skip this because it failed to downlaod sth at first and I just place the binary on PATH without re-run the post-script.
