### ISSUE TITLE
Add ability to display text inside ContextPad

### ISSUE THREAD

**Issue by fabio-bertone** [bpmn-io/diagram-js#415]
__Is your feature request related to a problem? Please describe.__

I would like to request a feature..related to a problem I'm having. In looking through the source there's no way to add a label within the context pad menu. You can only add images or font icons.

I would like the ability to change whether to display icons or text or both within the Context Pad menu. Currently it's only limited to images or icon font. This is very limiting and has a no-so-great user experience as it relies on the user to hover the icon in order to see what will happen before clicking.

__Describe the solution you'd like__

When overriding context pad options, I would like the ability to specify a label to display in lieu of an image or css icon. Or have a label in addition to an icon. Similar to the Popup menu.

__Describe alternatives you've considered__

None.

__Additional context__
Trying to do what's in the screenshot:
![Screen Shot 2019-10-03 at 3 48 00 PM](https://user-images.githubusercontent.com/54636313/66159068-388ca380-e5f5-11e9-8457-14ed73efe952.png)

**Comment by philippfromme** [comment]
I don't think we're going to modify the context pad in the near future. My suggestion would be to build your own context pad which shouldn't be too hard. Have you thought about that option?

**Comment by fabio-bertone** [comment]
I have not. All the examples I've seen show how to override the ContextPadProvider which changes the icons shown but doesn't allow to change how it's presented. Is there a similar way to override the ContextPad? I'm using this through bpmn-js.

**Comment by philippfromme** [comment]
Here's a quick example: https://codesandbox.io/embed/bpmn-js-custom-context-pad-5z5l3

Next, you could override `ContextPad#getEntries` to create your own entries.

I'll close this ticket since we're not going to change the context pad anytime soon. As you can see you can easily change it.

**Comment by fabio-bertone** [comment]
ah awesome! Thank you.

**Comment by joeskeen** [comment]
@philippfromme looks like the codesandbox link is dead now. Could you please provide a new link or a Gist showing how you do that?

**Comment by nikku** [comment]
@joeskeen What exactly are you looking for? 

The context pad is just another form of overlay, so you may very well use the infrastructure [provided for overlays](https://github.com/bpmn-io/bpmn-js-examples/tree/main/overlays).

Or you override / replace the built-in [context pad](https://github.com/bpmn-io/diagram-js/blob/develop/lib/features/context-pad/ContextPad.js#L330) to re-use our existing extensible infrastructure (if you need it).
