### ISSUE TITLE
Improve entries providers for palette, context pad and popup menu

### ISSUE THREAD

**Issue by barmac** [bpmn-io/diagram-js#428]
__Is your feature request related to a problem? Please describe.__

Currently, the palette and context pad providers are not capable of removing entries added by other providers. For popup menu, there can be only one provider for specific id. This limits the extensibility options and usually forces to subclass the extended library's provider.

__Describe the solution you'd like__

* [x] Create a unified and powerful API for different types of providers:
  * [x] provider can add, update and remove entries
  * [x] provider can register itself with a priority
  * [x] provider is called via its `get[componentName][type]Entries` method and can either return the entries to be added (legacy behaviour) or a function that gets called with `entries` and returns the updated `entries`
* [x] Implement the feature for:
  * [x] context pad
  * [x] palette
  * [x] popup menu
* [x] Update JSDocs and examples:
  * [x] context pad
  * [x] palette
  * [x] popup menu

__Describe alternatives you've considered__

Leave it as it is.

__Additional context__

Related to https://github.com/camunda/camunda-modeler/issues/1486

**Comment by pinussilvestrus** [comment]
This could also improve the way we fiddling around with the entries inside the [Zeebe Modeler](https://github.com/zeebe-io/zeebe-modeler/tree/develop/client/src/app/tabs/bpmn/custom).
