### ISSUE TITLE
ZoomScroll - Ability to enable to use mouse wheel directly without ctrl key

### ISSUE THREAD

**Issue by mnp-mid** [bpmn-io/diagram-js#440]
ZoomScroll - Ability to enable to use mouse wheel directly without ctrl key

I would like to provide some code for the ability to use the mouse wheel directly without the use of the ctrl key. This code does not change any current behavior but provides a flag to enable / disable the ability with default false.

The variable names are all yours to change. It would be nice if you could take the code or provide similar ability.

_Which issue does this PR address?_
Found in:
https://forum.bpmn.io/t/zooming-or-vertical-scrolling-what-should-be-the-default-mouse-wheel-action/131

PR:
This is releated to the Pull Request at: https://github.com/bpmn-io/diagram-js/pull/434

Code:
What I mainly see is that the only change neccessary would be at

ZoomScroll.prototype._handleWheel = function handleWheel(event) {
   ...
   // var isZoom = event.ctrlKey;	  
   // =>
   var isZoom = this._isDirectZoomWithMouseWheel ? !event.ctrlKey && !event.shiftKey : 
   event.ctrlKey;
   ...
}

whereas the _isDirectZoomWithMouseWheel may be a property that can be changed via configuration.

export default function ZoomScroll(config, eventBus, canvas) {
  ...
  this._isDirectZoomWithMouseWheel = typeof config.isDirectZoomWithMouseWheel === 'undefined' ? DEFAULT_DIRECT_ZOOM_WITH_MOUSE_WHEEL : config.isDirectZoomWithMouseWheel;
}

**Comment by tdauth** [comment]
Hi, any updates on this? I saw that https://github.com/bpmn-io/diagram-js/pull/434 was rejected? We are using an older version and people are used to this behavior so it would be helpful if we could restore the behavior with some option.

**Comment by nikku** [comment]
We'll not built support for this in the core any time soon.
