### ISSUE TITLE
Target Always Selected After Connect

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/diagram-js#445]
__Describe the Bug__

Instead of the target of the interaction the target of the resulting connection is selected after connect. If the connection target is not the target of the interaction the wrong shape is selected afterward.

![selection-behavior](https://user-images.githubusercontent.com/7633572/76401689-97afca80-6382-11ea-8401-d1b0c46a92a6.gif)

__Steps to Reproduce__

1. Connect two shapes from target to source

__Expected Behavior__

The target of the interaction should be selected afterward.

**Comment by pinussilvestrus** [comment]
Closed via https://github.com/bpmn-io/diagram-js/commit/189b26c472c6304173ef7e60bcbb38cdd867c4aa
