### ISSUE TITLE
Add SHIFT + box select to add/remove to/from selection

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/diagram-js#471]
__Is your feature request related to a problem? Please describe.__

Selecting more than one element is currently possible through box select or CTRL + select/box select. Most applications support SHIFT + select/box select, too. I always find myself trying to use SHIFT before realizing that only CTRL is supported.

__Describe the solution you'd like__

Add SHIFT + select/box select.

__Describe alternatives you've considered__

Not adding it.

**Comment by nikku** [comment]
Let's do a quick round of research to see what is the most used shortcut to do that thing.

Happy to adjust / change our default, if other tools do things differently.

**Comment by nikku** [comment]
This behavior is especially odd as we do `SHIFT` + drag for multi selection. If I'd like to add an additional element to the mix I have to switch from `SHIFT` to `CTRL`.

![capture rrWtwB_optimized](https://user-images.githubusercontent.com/58601/83116584-433c0180-a0cc-11ea-8707-acc2cf4d8ba9.gif)

**Comment by dlavrenuek** [comment]
@philippfromme I would like to contribute and added a PR that implements this feature as well as test coverage: https://github.com/bpmn-io/diagram-js/pull/493

I also confirmed the functionality with a manual test by running the the `/example` application

Happy Hacktoberfest!
