### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by FrankiePo** [bpmn-io/diagram-js#481]
Currently typescript is de-facto the main standard in typed javascript.

Are there any changes in plans on providing typescript definitions?

Typescript significantly improves the development process for new modules.

#227 old discussion

**Comment by pinussilvestrus** [comment]
Please confirm to [this issue](https://github.com/bpmn-io/bpmn-js/issues/1343#issuecomment-674956722) that it's unlikely that we're going to implement typescript support in the near future. There is also some discussion around that in [this issue](https://github.com/bpmn-io/bpmn-js/issues/1002).
