### ISSUE TITLE
Migrate code base to ES6

### ISSUE THREAD

**Issue by FrankiePo** [bpmn-io/diagram-js#482]
As of version 1.0.0 this library exposes ES modules.
We use bundler such as Webpack or Rollup to bundle library

Why are we still using es4 syntax with prototypes?
All modern browsers support es5 at least.

Even if we want support old ones in any case we use webpack for bundling.

For example, we can change this "class":
```js
import {
  create
} from '../model';

import { assign } from 'min-dash';

/**
 * A factory for diagram-js shapes
 */
export default function ElementFactory() {
  this._uid = 12;
}


ElementFactory.prototype.createRoot = function(attrs) {
  return this.create('root', attrs);
};

ElementFactory.prototype.createLabel = function(attrs) {
  return this.create('label', attrs);
};

ElementFactory.prototype.createShape = function(attrs) {
  return this.create('shape', attrs);
};

ElementFactory.prototype.createConnection = function(attrs) {
  return this.create('connection', attrs);
};

/**
 * Create a model element with the given type and
 * a number of pre-set attributes.
 *
 * @param  {string} type
 * @param  {Object} attrs
 * @return {djs.model.Base} the newly created model instance
 */
ElementFactory.prototype.create = function(type, attrs) {

  attrs = assign({}, attrs || {});

  if (!attrs.id) {
    attrs.id = type + '_' + (this._uid++);
  }

  return create(type, attrs);
};
```
to the modern one:
```js
import {
  create
} from '../model';

import { assign } from 'min-dash';

/**
 * A factory for diagram-js shapes
 */
export default class ElementFactory {
  constructor() {
    this._uid = 12;
  }

  createRoot(attrs) {
    return this.create('root', attrs);
  }

  createLabel(attrs) {
    return this.create('label', attrs);
  }

  createShape(attrs) {
    return this.create('shape', attrs);
  }

  createConnection(attrs) {
    return this.create('connection', attrs);
  }

  /**
   * Create a model element with the given type and
   * a number of pre-set attributes.
   *
   * @param  {string} type
   * @param  {Object} attrs
   * @return {djs.model.Base} the newly created model instance
   */
  create(type, attrs) {

    attrs = assign({}, attrs || {});

    if (!attrs.id) {
      attrs.id = type + '_' + (this._uid++);
    }

    return create(type, attrs);
  }
}
```

I can do the most migration by myself, but will it be ever merged?

**Comment by nikku** [comment]
We've recently dropped IE 11 so indeed, this would be something that works now.

However, what is the actual benefit, i.e. why invest time into this right now?

**Comment by nikku** [comment]
By the way, `class` is an ES6, not a ES5 feature :wink:.

**Comment by FrankiePo** [comment]
Actually, it will be easier to generate types for typescript. They will be more accurate.
The code base will be more readable.

You shouldn't invest time in this right now. Lets community do the staff.

The main problem which I found PhantomJS can't test this syntax. But AFAIK it is depricated and not maintained. Probably we can drop it and use Headless Chrome/Firefox only

**Comment by pinussilvestrus** [comment]
> You shouldn't invest time in this right now. Lets community do the staff.

good approach.

**Comment by FrankiePo** [comment]
Created PR as example of conversion. Is it relevant and ok?
Tested in Headless Chrome.

Should I continue my work?

**Comment by nikku** [comment]
Sorry for not getting back to you earlier. I'll look into this topic the next days and see if it is a viable direction forward. Automatic migration is one of the crucial requirements and I'm happy you've provided [lebab](https://github.com/lebab/lebab) as a potential solution.

**Comment by nikku** [comment]
To wrap up my investigation, there is a few things that are worth noting.

* Migration will aid discovery and tooling. I.e. with ES6 classes we get proper tooling using common JS language services. With our prototypical inheritance we don't (at least I did not, yet).
* We'd need to decide what to migrate. Migrating classes and var/const as well as getting rid of _self_ by using arrow functions sound like reasonable candidates but we should not rush things.
* As mentioned in https://github.com/bpmn-io/diagram-js/pull/483#issuecomment-703691236 migration will remain a manual task, even when being aided by [lebab](https://github.com/lebab/lebab).
* Migration will be a major change, as it breaks certain documented usage patterns. As an example, you cannot do the following after `RuleProvider` turned into a ES6 class:

    ```javascript
    function CustomRules(eventBus) {
      RuleProvider.call(this, eventBus);
      // ^
      // blows up, as an ES6 class must be invoked with *new*
    }
    ``` 

Concluding, this is nothing we quickly do. Rather I propose that we commit to it and migrate library by library in a combined efford.

**Comment by nikku** [comment]
In the course of the investigation I created a small supporting script that can be found [here](https://gist.github.com/nikku/6103cd0cc7a5b081b35b5cdbc3d13946).

**Comment by nikku** [comment]
As of Q1 2021 we get proper IDE tooling if we fix our JSDoc annotations. 

Closing this issue, as introducing classes will be a major breaking change that we'll likely not act upon in the near future.

Related: https://cdn.statically.io/gh/nikku/types-without-typescript/v0.0.2/presentation.html.
