### ISSUE TITLE
Remove snapsvg

### ISSUE THREAD

**Issue by nikku** [bpmn-io/diagram-js#50]
Performance studies (bpmn-io/bpmn-js#126) have shown that snapsvg is really slow. Replacing it will result in improved rendering performance and better code structure.
### Things to replace
- [ ] DOM manipulation (attribute handling, node creation, insertion, remove)
- [ ] intersection algorithm
### Path

Build utility methods to interact with SVG to better separate SVG concerns from diagram-js:
###### snapsvg: explicit, SVG hiding syntax

``` javascript
var paper = Snap.create();
var group = paper.group();

group.attr({ transform: ' .... ' });
```
##### own implementation: native SVG + utility methods

``` javascript
var svg = tsvg.create('svg');
var group = tsvg.append(tsvg.create('g'), svg);

tsvg.attr(group, { transform: ' .... ' });
```

**Comment by pedesen** [comment]
Review Hints:

* [bpmn-js] several positioning test cases got fixed, some of them are more robust now: https://travis-ci.org/bpmn-io/bpmn-js/builds/170717000
* [diagram-js] allowed case statement fallthrough to pass eslint

TODO:
* [diagram-js] still failing test cases regarding createText: https://travis-ci.org/bpmn-io/diagram-js/builds/170464116
