### ISSUE TITLE
Fix JSDoc type definitions on service APIs

### ISSUE THREAD

**Issue by nikku** [bpmn-io/diagram-js#502]
__What should we do?__

Related to https://github.com/bpmn-io/diagram-js/issues/501 we should fix the JSDoc types on service APIs so that proper type hinting can be done.

__Why should we do it?__

This allows introspection of API usage and, within a TypeScript code base, allows users to detect structural API miss-use.

----

Child of https://github.com/bpmn-io/bpmn-js/issues/1002

Depends on https://github.com/bpmn-io/diagram-js/issues/501

**Comment by philippfromme** [comment]
Closed by https://github.com/bpmn-io/internal-docs/issues/688. [diagram-js@12](https://www.npmjs.com/package/diagram-js/v/12.0.0) includes type declarations.
