### ISSUE TITLE
Slow rendering

### ISSUE THREAD

**Issue by jetdream** [bpmn-io/diagram-js#510]
When a diagram has hundreds of elements the rendering becomes very slow (can be 10-20 seconds before appear).

Chrome profiler shows the most of the time is spent on the line 61: `textBBox = fakeText.getBBox();`

of the method:
https://github.com/bpmn-io/diagram-js/blob/2351234a87c5586e3d17fb2c45b6795bf561d589/lib/util/Text.js#L47-L80

To ensure this is a problem I've tried a solution with simple cache - **bboxCache** and improved performance by ~10x for second rendering.

This solution helps little for first rendering, but it works for me well enough since in my case a diagram appears many times in different contexts. Might be there is another way how to improve it even further.

```
const bboxCache = new Map();

function getTextBBox(text, fakeText) {

    let cachedResult = bboxCache.get(text);
    if (cachedResult) {
        return cachedResult;
    }

    fakeText.textContent = text;

    var textBBox;

    try {
        var bbox,
            emptyLine = text === '';

        // add dummy text, when line is empty to
        // determine correct height
        fakeText.textContent = emptyLine ? 'dummy' : text;

        textBBox = fakeText.getBBox();

        // take text rendering related horizontal
        // padding into account
        bbox = {
            width: textBBox.width + textBBox.x * 2,
            height: textBBox.height
        };

        if (emptyLine) {

            // correct width
            bbox.width = 0;
        }

        bboxCache.set(text, bbox);

        return bbox;
    } catch (e) {
        let bbox = { width: 0, height: 0 };
        bboxCache.set(text, bbox);
        return bbox;
    }
}
```

**Comment by azeghers** [comment]
Hi jetdream,

Could you provide me with some context as to what you're trying to build, what you're rendering, maybe an example or a codesandbox so I can look into how to make it more efficient?

**Comment by jetdream** [comment]
Hi Alexis @azeghers 
I'm using bpmnjs to edit BPMN processes, and to visualize overall process performance.

To demonstrate the issue I drafted a complex diagram on https://bpmn.io - [diagram.bpmn.zip](https://github.com/bpmn-io/diagram-js/files/5705385/diagram.bpmn.zip) and actually was surprised that even more complex diagram rendered almost instantly.

Initially I was confused, but after research I found that I've added a simple shadow styling to the diagram which greatly affected the performance:
```
.djs-container svg {
    filter: drop-shadow( 2px 2px 2px rgba(0,0,0,0.3));
}
```
This makes much harder for the renderer to calculate text bounding box.

Taking in account that issue appeared in my very specific case I'm not sure if it should be considered as a bug.
But certainly this is the place for overall performance improvement.

**Comment by azeghers** [comment]
Thank you for your follow-up and the additional context.
Having discussed with a member of my team, we have come to the conclusion that a truly efficient and flawless caching might be too big of an effort. The one you wrote, though functional for a simple re-render, wouldn't take into account font, text size changes or invalidation for instance.
Your suggestions will be kept in mind and we might refine the algorithm in the future.

**Comment by jetdream** [comment]
I understand.
Another direction for performance improvement is to provide an ability to save already rendered SVG and then use this SVG when a diagram will be loaded next time to completely avoid the need for rendering.
In my case I would store this SVG on browser's IndexedDB storage.

**Comment by nikku** [comment]
We'll likely not implement deep caching in the future. 

Regardless, we'd be interested in potential improvements, if they apply in a general manner. Happy to see your contribution.

Let's close this particular issue for now.
