### ISSUE TITLE
Test suite fails on MacOS

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/diagram-js#520]
__Describe the Bug__

On the current `master` branch, `npm run all` fails on MacOS

![image](https://user-images.githubusercontent.com/9433996/104743719-4ca5d700-574c-11eb-8026-403aaa7ebbf4.png)

I first thought it would be a problem with my setup, but actually it is reproducible when we configure mac os in our GitHub Action, cf. [to this build](https://github.com/bpmn-io/diagram-js/runs/1709293606?check_suite_focus=true) to get more information.

__Steps to Reproduce__

1. `git checkout master`
2. `npm install`
3. `npm run all`

__Expected Behavior__

Everything works fine on MacOS.

__Environment__

Please complete the following information:

 - OS: macOS 10.15.7
 - Library version: current `master`

**Comment by pinussilvestrus** [comment]
Furthermore, I think it would make a lot of sense to test all environments on CI, not only Linux.

Cf. to this [build matrix](https://github.com/bpmn-io/vs-code-bpmn-io/blob/master/.github/workflows/ci.yml#L8).

**Comment by pinussilvestrus** [comment]
@barmac Can you maybe verify?

**Comment by barmac** [comment]
Same here.

**Comment by pinussilvestrus** [comment]
Root cause:

* for the tests that fail, we set up `ctrlKey: true`, e.g. in [`SelectionBehaviorSpec`](https://github.com/bpmn-io/diagram-js/blob/develop/test/spec/features/selection/SelectionBehaviorSpec.js#L365)
* this is not enough for Mac environments, since we identify `metaKey` to indicate primary modifiers, cf. [these lines of code](https://github.com/bpmn-io/diagram-js/blob/master/lib/util/Mouse.js#L42-L48)
* the documentation is also outdated, for 5 years now: https://github.com/bpmn-io/diagram-js/commit/82b1a5d347d8c5862c6bec1a39d9b3a2d0161ba0

![image](https://user-images.githubusercontent.com/9433996/104935999-3bf39c00-59ac-11eb-90be-47e5c40a98f2.png)

**Comment by pinussilvestrus** [comment]
Closed via 3180fa9
