### ISSUE TITLE
EventBus#once Can Lead to Endless Loop

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/diagram-js#524]
Due to the [implementation of `once`](https://github.com/bpmn-io/diagram-js/blob/v7.1.0/lib/core/EventBus.js#L183) which only removes the callback after it was executed the following code results in an endless loop:

```javascript
eventBus.once("foo", () => {
  eventBus.fire("foo");
});

eventBus.fire("foo");
```

My expectation would be that `once` means that firing the same event inside the callback doesn't call it again. The implementation [was changed](https://github.com/bpmn-io/diagram-js/commit/efd184dbaebecf6d770c7e2c5cb16d7949b27013#diff-36c07e37c1a94f9261aa2793bec072781fad7021ffe583be653c166cd3cd21e0) to fix another [issue](https://github.com/bpmn-io/diagram-js/issues/293) leading to this regression, as I would call it.

Related to https://github.com/bpmn-io/diagram-js/issues/525

**Comment by nikku** [comment]
Agreed. Happy to take a contribution that improves this.

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/diagram-js/issues/526.
