### ISSUE TITLE
Align elements when nothing is selected delivers into ERROR in console. 

### ISSUE THREAD

**Issue by quintanamartin** [bpmn-io/diagram-js#533]
When user clicks in align elements without a selection, there is an error in the console that might be annoying for us, the developers. The error triggers in getMiddleOrTop function, first and last are undefined so there's no X or Y defined and this triggers the console error. I know this is not a problem for user, but it is for us. 

My simple solution: 
function getMiddleOrTop(first, last) {
        if (first === undefined || last === undefined) {
            return;
        } else {
            return Math.round((first[axis] + last[axis] + last[dimension]) / 2);
        }
    }

**Comment by pinussilvestrus** [comment]
Can you please update the issue to [fit our guidelines](https://github.com/bpmn-io/diagram-js/issues/new?assignees=&labels=bug&template=BUG_REPORT.md)? It's otherwise hard to understand your problem.

**Comment by nikku** [comment]
Closing this issue as we miss the context in which that problem occurs.

Please [update your issue](https://github.com/bpmn-io/diagram-js/issues/533#issuecomment-773840349) with relevant details and we may have another look.
