### ISSUE TITLE
Create a Listener Event that fires when an Overlay is added/changed/removed in Task Element

### ISSUE THREAD

**Issue by cancius-cv** [bpmn-io/diagram-js#542]
I have created an Overlay which is rendered in the Task Element, it can also be saved in XML thanks to [this function](https://github.com/bpmn-io/bpmn-js-embedded-comments/blob/master/lib/util.js#L1) and by creating a custom model descriptor following [this example](https://github.com/bpmn-io/bpmn-js-examples/tree/master/custom-meta-model).

Issue:
The created overlay gets saved only when I change/add/remove some Element in the BPMN Diagram, meaning the new XML for overlays is generated only after `eventBus.on('elements.changed')` occurs. Everything related to Overlays does not get listened by that `elements.changed` event and by any other from bpmn-js. 

I have understood that diagram-js is built on bpmn-js or vice versa, therefore it would make sense to have overlays supported by bpmn-js. Furthermore, I experienced from the forum, that a lot people are extending the diagrams using overlays, that at some point have to be saved in XML.

Please create an event that listens to overlays changes, respectively that listens to when an overlay is added/removed/changed in BPMN diagram.

**Comment by nikku** [comment]
To better understand your use-case it could make sense if you provide an end-to-end example of what you're trying to achive.

Do you build a editor on diagram-js? Or do you build an editor on top of bpmn-js? Do you use the editor or viewer to plug-in your overlays?

Based on these questions different solutions may suite your needs.
