### ISSUE TITLE
Hello, is there any API for beautifying Diagram like video at present

### ISSUE THREAD

**Issue by hehanli101** [bpmn-io/diagram-js#557]
https://user-images.githubusercontent.com/39009226/124094117-0d194000-da8b-11eb-8f9e-52cc23c99861.mp4

**Comment by pinussilvestrus** [comment]
As far as I know, there is not something like that.

I think asking the question in our [forum](https://forum.bpmn.io/) would be better. GitHub issues are better suited for feature requests and bug reports. Thanks!
