### ISSUE TITLE
Typeface: Replace Arial with Inter

### ISSUE THREAD

**Issue by currandwyer** [bpmn-io/diagram-js#572]
__Is your feature request related to a problem? Please describe.__

We currently use Arial when rendering BPMN. Arial was designed for IBM in 1982 to avoid paying licensing fees for Helvetica. It works visually because it is generic, but it was not designed for use on screens and its legibility suffers as a result. Newer, screen optimized typefaces are available for us to explore. 

Arial does have the advantage of being universally available everywhere, but there are ways of embedding fonts so they reliably appear as the primary option, while still relying on Arial as a fallback. 

__Describe the solution you'd like__

We should consider using Inter, an excellent open source typefaces designed to be used on screens at all sizes.

We have already spent a bit of time doing preliminary exploration and testing of Inter from a design and development perspective. Now we need to agree on what is the best way to embed Inter within diagram-js. One option is to integrate Inter with the BPMN font, so they're bundled and loaded together.

Inter is a variable font with highly [customisable dynamic metrics](https://rsms.me/inter/dynmetrics/) that can be used to optimize the font's tracking and leading for our specific use case. I would like to do a bit of pair programming/design in a branch to determine the exact right settings for Inter in bpmn-js.

__Describe alternatives you've considered__

We could use a system-UI font, but it would lead to inconsistency in the experience.

Another obvious choice might be IBM Plex, a screen font that we use everywhere else in the UI. For our BPMN diagrams, we want a generic, neutral typeface like Arial. Plex does not fit the bill.

__Additional context__

[Inter GitHub Repo](https://github.com/rsms/inter)
[Inter Lab](https://rsms.me/inter/lab/)

<img width="457" alt="Screen Shot 2021-09-23 at 16 30 45" src="https://user-images.githubusercontent.com/11223953/136168187-f76fc685-bad4-4907-950b-0afdc9d22914.png">

**Comment by nikku** [comment]
Closing this as won't fix. Let's see if such an initiative emerges again.
