### ISSUE TITLE
8.1.0 causes bpmn js i18N to fail. The switchover will be restored in 7.8.1

### ISSUE THREAD

**Issue by zxiaozhou** [bpmn-io/diagram-js#618]
__Describe the Bug__
1. bpmn i18n does not take effect when the diagram-js dependency is upgraded to 8.1.0
2. bpmn i18n takes effect when the diagram-js dependency is downgraded to 7.8.1

Please complete the following information:

 - Browser: [e.g. IE 11, Chrome 69] 97
 - OS: [e.g. Windows 7] mac 12.2
 - Library version: [e.g. 2.0.0] bpmn js 8.9.1

**Comment by pinussilvestrus** [comment]
Can you share an example project or a [CodeSandbox](https://codesandbox.io/s/heuristic-meninsky-hqezx) to showcase the broken behavior?

**Comment by pinussilvestrus** [comment]
Any updates on this one @zxiaozhou?

**Comment by zxiaozhou** [comment]
@pinussilvestrus I went back to my hometown recently and didn't bring my computer back to provide cases

**Comment by pinussilvestrus** [comment]
I'm sorry to hear that.

I'll close this issue due to a missing example. Feel free to re-open once you can provide further information.
