### ISSUE TITLE
Make `keyboard` binding implicit / remove ability to bind to any element

### ISSUE THREAD

**Issue by nikku** [bpmn-io/diagram-js#661]
__Is your feature request related to a problem? Please describe.__

For historical reasons our users had to bind `keyboard` to any element on the page, may it be document, or the diagram container. With https://github.com/bpmn-io/diagram-js/pull/662 we make the diagram canvas browser selectable; as such we can safely figure out if the canvas has focus and keyboard bindings shall be accounted for.

Because of that we want to remove the bind anywhere `keyboard#bindTo` / `keyboard#bind(element)` APIs.

__Describe the solution you'd like__

* Keyboard can be bound and unbound, _however_ it will always be bound to the canvas
* Binding keyboard to a particular element is removed
* Configuring element to be bound to via `keyboard.bindTo` is removed
* Proper error messages indicate old use
* API to focus the diagram (`canvas.focus()`, and potentially `diagram.focus()` as a proxy) exist
* To be considered: The canvas fires `focus` and `blur` events that I can hook into to register global keyboard shortcuts
* Once the canvas is focused, then we spend reasonable amount of effort to keep it focused / restore focus once on canvas edit operations happened (https://github.com/bpmn-io/diagram-js/pull/662#issuecomment-2314722118)

__Describe alternatives you've considered__

Keep stuff and magic as is.

__Additional context__

This is a major improvement UX wise.

**Comment by marstamm** [comment]
@nikku , assigned to you for now to clarify what is needed to enable HTO team

**Comment by nikku** [comment]
@vsgoulart I'll not be able to follow up on this in the next days, but will revisit end of March.

**Comment by barmac** [comment]
Assigning to @jarekdanielak to assess in a timebox manner.

**Comment by nikku** [comment]
Explanatory scetch, based of discussion with @jarekdanielak:

![image](https://github.com/user-attachments/assets/98180f0a-1c18-474f-a6bc-148fdc4b8b16)

**Comment by nikku** [comment]
Existing ways to indicate breaking changes (APIs no longer working or changed) - https://github.com/search?q=repo%3Abpmn-io%2Fdiagram-js%20console.warn&type=code.

**Comment by nikku** [comment]
Other editors, e.g. [code mirror](https://codemirror.net/) are great examples for friendly, and accessible integration into the browser.
