### ISSUE TITLE
Mouse-wheel zoom usability

### ISSUE THREAD

**Issue by EloProf** [bpmn-io/diagram-js#67]
In my current use case I have div for my diagram that is basically full width and is at the top of the page . Because of a lot of content below the diagram the page also has to scroll down.

If you try to scroll down now you will immediately stop scrolling and start zooming the diagram once your cursor touches the diagram area. This is quite an issue for usability and should probably adressed if possible. Moving the diagram around doesn't have this issue because it relies on drag-and-drop.

Unfortunately I can't really think of a very good solution for this. Perhabs enable scrolling after a `onclick` and disable it after another `onclick`?

**Comment by nikku** [comment]
Unfortunately it is impossible to workaround the mouse wheel zoom interaction at the moment. The only option you have is to put an overlay on top of the diagram and remove it on click. This would result in the behavior you suggested.

We were thinking about reworking our diagram interaction in one of the next releases.

One of the core issues to tackle is that users need to get more control about when to zoom/scroll. I see three options:

* manually activate
* google maps (current) style
* web style (mouse wheel scrolls, if at end, continues scrolling the page contents; CTRL+mouse wheel zooms)


Do you have any thoughts on this?

**Comment by EloProf** [comment]
In my opinion the manual activation option should be added to the API no matter what. You should be able to enable and disable moving and scrolling independently through method calls and also through creation options.

The problem with the google maps style I am seeing is that the map is either full screen, like on maps.google.com, or it is mostly embedded in pages that don't need to scroll or at the bottom of scrolling pages, so this issue rarely arises with it.

The CTRL style isn't a viable option in my opinion. Users don't expect having to use keys to enable special functionality on websites. Furthermore CTRL + mousewheel is already bound to changing the page zoom in many browsers.

Perhabs it would be best to show an overlay with controls on the diagram that features movement and especially zoom controlls like google maps does it? In this case you could disable mouse zoom by default and add a button to enable and disable it.

An overlay would also have the benefit of making it clearer to new users that the diagram can be interacted with and is not just a still image.
