### ISSUE TITLE
Implement popupMenu with improved UI

### ISSUE THREAD

**Issue by smbea** [bpmn-io/diagram-js#686]
__What should we do?__
We want to replace the old popup UI menu with a new and improved UI, which includes searching. 

**To do:**
- [x] Integrate diagram-js-ui
- [x] Implement new UI and replace old popupMenu
    - Have backwards compatibility
    - Improve popup menu foundations
       - Allow grouping, descriptions, documentation url 
- [x] Prioritize and fix most pressing [known issues](https://github.com/bpmn-io/bpmn-js-connectors-extension/issues)
    - Keyboard accessible
    - Popup menu container within canvas
    
 Initial implementation concluded by https://github.com/bpmn-io/diagram-js/pull/687
   
 **Identified bugs/improvements:**
- [x] https://github.com/bpmn-io/diagram-js/issues/695
   
__Why should we do it?__
Preparation to support append anything - see https://github.com/bpmn-io/bpmn-js/issues/1627

---
Child of https://github.com/bpmn-io/bpmn-js/issues/1627

**Comment by marstamm** [comment]
Good point regarding the min-width. I like the option to make it configurable, so it works for both cases
