### ISSUE TITLE
Arrow keys don't work in popup menu 

### ISSUE THREAD

**Issue by smbea** [bpmn-io/diagram-js#701]
__Describe the Bug__

Arrow keys don't work in popup menu when search is turned off

__Steps to Reproduce__

https://user-images.githubusercontent.com/28307541/203007560-46020f63-1b4d-47fe-9dd0-7dae0cdc21ef.mov

1. open popup menu for sub process
2. use arrow up/down
3. see that element moves instead of navigating the menu

__Expected Behavior__

The arrow keys should result in menu navigation

__Environment__

Please complete the following information:

 - Library version: 11.0.0

**Comment by nikku** [comment]
Further root causing:

* adding `tab-index=-1` to the popup menu allows us to focus it programmatically
* _HOWEVER_: Keyboard will always use the capture phase to intercept events; as a result we cannot hook in before it :see_no_evil:
