### ISSUE TITLE
Specialize popup menu classes (with prefix)

### ISSUE THREAD

**Issue by smbea** [bpmn-io/diagram-js#703]
__What should we do?__

Investigate if other djs elements maintain specialized prefixed classes (eg: `djs-popup-...`) at all times, and decide if we should follow this for the popup menu.

__Why should we do it?__

To have a clear understand of how djs elements should be implemented and to keep consistency with other djs elements.

**Comment by nikku** [comment]
> Since this causes more breaking changes, does it mean we need another major release?

If we go for this (and follow up soon), let's bake it into a 11.x minor release. 

11.x has not been adopted to date.

**Comment by nikku** [comment]
You could also mark 11.x as `next` on `npm` to be sure.
