### ISSUE TITLE
False property overflow:overlay for selector .djs-popup-results

### ISSUE THREAD

**Issue by jurgenhaas** [bpmn-io/diagram-js#726]
__Describe the Bug__

The file diagram-js.css, which is included in this package and also in bpmn-js, where we are using it in the Drupal integration, contains the selector `.djs-popup-results` which defines the property `overflow: overlay;`. As a result, the scrollbar for the element template chooser is missing and users can't scroll in the results.

If we replace that with `overflow: scroll;`everything works again like before.

**Comment by nikku** [comment]
Thanks for the report. Fixed.
