### ISSUE TITLE
Allow to collapse/expand groups in popup menu

### ISSUE THREAD

**Issue by smbea** [bpmn-io/diagram-js#764]
### Is your feature request related to a problem? Please describe.

Popup menu may contain a lot of entries at times. Search is helpful to navigate those but you may have to scroll through a whole group you are not interested in to get to the items you need.

### Describe the solution you'd like

Allow to collapse and expand groups in popup menu. 

### Describe alternatives you've considered

Keeping as is

**Comment by barmac** [comment]
This seems to belong to the create-append-anything, doesn't it?

**Comment by nikku** [comment]
What is the user journey we have in mind that this feature request would support?

I'm not sure the user ever wants to scroll to all available options, and wants to do that "efficiently" by collapsing individual sections.

If at all, then these choices would need to be persistent; but then again we could invest into opinionated, contextual suggestions, too.

And after all, there is search, which helps quick discovery use cases.

**Comment by smbea** [comment]
cc @YanaSegal (this issue derived from the discussion about search in the popup menu)

**Comment by nikku** [comment]
@YanaSegal @smbea I#m inclined to fix this as `won't fix` as I do not see this as a valuable (and easy to use) addition to our existing popup menu UX.

**Comment by YanaSegal** [comment]
My assumption is if the list becomes too long, it would be helpful to collapse irrelevant groups. At the same time, It could be excessive addition for this feature and search is enough to filter irrelevant results. @smbea wdyt?

**Comment by smbea** [comment]
I think it could be useful. Especially for users who aren't sure what they are looking for.

But it would require some effort to do it. I'm also confident that we will have some feature requests for that if it annoys users. So I am ok with closing ad `won't fix`

**Comment by nikku** [comment]
Let's close it and revisit with future user feedback we receive.
