### ISSUE TITLE
Add opportunity to register custom handler on zooming type events

### ISSUE THREAD

**Issue by corocoto** [bpmn-io/diagram-js#789]
### Is your feature request related to a problem? Please describe.

I added an opportunity to zoom my bpmn diagram scene. But the problem is that I also want to show the percent of zooming.
As example, I want to update this value after clicking on properly buttons (+, -) or via mouse wheel manipulation.

I suppose, the best way is opportunity to register custom handler on this type of events. It can be look like: `eventBus.on('scene.zoom', LOW_PRIORITY, [YOUR CUSTOM HANDLER])`

### Describe alternatives you've considered

I think, the problem also can be fix, if a developer deside to create a wrapper uppon [`_zoom` method](https://github.com/bpmn-io/diagram-js/blob/develop/lib/navigation/zoomscroll/ZoomScroll.js#L195). But it's not an optimal way.

**Comment by nikku** [comment]
@corocoto We fire [`canvas.viewbox.changed`](https://github.com/bpmn-io/diagram-js/blob/develop/lib/core/Canvas.js#L1099). I believe this should give you all tools needed to implement a `%` view of of zoom levels?

**Comment by corocoto** [comment]
@nikku, yeah, it's that I need. Thanks a lot!
