### ISSUE TITLE
Running Sample - common.js

### ISSUE THREAD

**Issue by florianpirchner** [bpmn-io/diagram-js#79]
Hi,

i tried to run the examples. But common.js seems to be missing. For the diagram.js i changed the path.

So the call to require() produces an error.

Thanks for any hints...

Best, Florian

**Comment by nikku** [comment]
The example itself is outdated and will not run like this anymore.

If you want to look into examples using diagram-js, run the diagram-js test suite via `cd diagram-js && TEST_BROWSERS=Chrome grunt auto-test` (adapt that to your operating system).
