### ISSUE TITLE
Drop `hammerjs` dependency

### ISSUE THREAD

**Issue by nikku** [bpmn-io/diagram-js#796]
### What should we do?

Drop hammerjs as a dependency.

### Why should we do it?

We rely on [hammerjs](https://github.com/bpmn-io/diagram-js/blob/develop/package.json#L82) for touch recognition, however this library is long dead, as it seems: https://github.com/hammerjs/hammer.js/issues/1278.

**Comment by Samyssmile** [comment]
hammerjs has also security issues.

**Comment by Samyssmile** [comment]
There is also a Security Issue with hammer.js because it using loadash as dependency.

**Comment by nikku** [comment]
@Samyssmile Please reference where exactly hammer.js uses lodash as a dependency. I've asked you previously and [could not find a production](https://github.com/search?q=repo%3Ahammerjs%2Fhammer.js%20lodash&type=code) dependency myself.

**Comment by nikku** [comment]
Moving this to `ready`. Let's consider it for a Q1 internal improvement, as it blocks us in other areas, too (`hammerjs` is not an ES module, preventing users to load touch support as an ES module).

**Comment by philippfromme** [comment]
We've decided to simply remove `hammerjs` without replacement for now. Touch integration could be reintroduced using an extension rather than having it in the core.
