### ISSUE TITLE
Add a `refresh` function to the `popupMenu` object

### ISSUE THREAD

**Issue by marcellobarile** [bpmn-io/diagram-js#804]
### Is your feature request related to a problem? Please describe.

With https://github.com/camunda/web-modeler/issues/6066 we are adding to the web-modeler the capability to import element templates from the marketplace;
once this is done via a pop-over dialog, the user should go back to the diagram following a non-interrupting UX; the just imported element templates should be listed in the element templates list while it's opened.

### Describe the solution you'd like

We are `hacking` the `popupMenu` in the web-modeler by programmatically closing and re-opening it.
This solves the issue because it implicitly forces a new rendering.

This could be avoided if the `popupMenu` was exposing a `refresh` method that computes and renders the entities list from scratch.

In the alternative, the list in the UI could be internally refreshed as soon as new templates are set via the `elementTemplatesLoader`.

### Additional context

First, we update the list of templates by calling `elementTemplatesLoader.setTemplates` as soon as we have imported new element templates.

Secondly, this is the `hacky` solution implemented in the web-modeler to "propagate" the change also to the UI (without having to go away from the diagram, or unselecting and reselecting the element and other actions that might create friction during the modelling):
```
try {
    if (popupMenu.isOpen()) {
       const { target, position, options, className: providerId } = popupMenu._current;
          
       popupMenu.close();
       popupMenu.open(target, providerId, position, options);
    }
} catch (err) {
    console.log(err);
}
```

**Comment by barmac** [comment]
If I understand you correctly, the required feature is to be able to reload the content of the popup menu without reopening.
Given a popup menu is open, when an external system triggers `refresh`, the popup menu should retrieve the entries again and re-render its contents. Is that correct?

Still, I can imagine that even such expansion of the API may appear to be too small soon. If a user requests additional entries which are loaded asynchronously, they may expect some kind of loader/spinner for which there is no place in the current, synchronous API. Perhaps we need to have a popup menu which could receive entries asynchronously? Or a way to hook up into what component is displayed?

**Comment by marcellobarile** [comment]
@barmac 
> Is that correct

Correct :)

>  I can imagine that even such expansion of the API may appear to be too small soon. If a user requests additional entries which are loaded asynchronously, they may expect some kind of loader/spinner for which there is no place in the current, synchronous API

My gut feeling is that this depends on the direction that we want to take in the future; right now the async business logic to select / fetch / import new templates is handled by different components of the web-modeler, meaning that when we set new templates in the `popupMenu` we already have everything in place.

**Comment by nikku** [comment]
To me this sounds like a reasonable request. We already use such functionality [internally](https://github.com/bpmn-io/diagram-js/blob/develop/lib/features/popup-menu/PopupMenu.js#L85).

**Comment by barmac** [comment]
There is no capacity in this iteration, we leave it in `ready` to be prioritized in the next iteration.

**Comment by philippfromme** [comment]
@barmac You are assigned to this issue. Are you planning to work on it anytime soon?

**Comment by philippfromme** [comment]
@barmac As discussed, I will take over this issue.

**Comment by philippfromme** [comment]
Closed by https://github.com/bpmn-io/diagram-js/pull/860.
