### ISSUE TITLE
getNextPosition ts type bug in AutoPlaceUtil.d.ts

### ISSUE THREAD

**Issue by d591342** [bpmn-io/diagram-js#843]
### Describe the Bug
in diagram-js\lib\features\auto-place\AutoPlaceUtil.d.ts
/**
 * Get free position starting from given position.
 *
 * @param source
 * @param element
 * @param position
 * @param getNextPosition
 *
 * @return
 */
export function findFreePosition(source: Shape, element: Shape, position: Point, getNextPosition: (element: Element, position: Point, connectedAtPosition: Element) => Element): Point;
return type of getNextPosition seems need to be Point, but now is Element 

### Steps to Reproduce

return findFreePosition(
      source,
      element,
      position,
      generateGetNextPosition(nextPositionDirection),
    ) 
  will report compilation errors in ts :

Argument of type '(element: Element, previousPosition: Point, connectedAtPosition: Element) => Point' is not assignable to parameter of type '(element: Element, position: Point, connectedAtPosition: Element) => Element'.
  Type 'Point' is not assignable to type 'Element'.
    Property 'id' is missing in type 'Point' but required in type '{ id: string; businessObject?: any; }'.

71       generateGetNextPosition(nextPositionDirection),
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by philippfromme** [comment]
I will check this out.
