### ISSUE TITLE
Incorrect fit viewport zoom after browser resize

### ISSUE THREAD

**Issue by SebastianStamm** [bpmn-io/diagram-js#85]
When I open a complex diagram, e.g. http://demo.bpmn.io/s/application-processing with a non-maximized browser window, the diagram is zoomed out, so that it fits the viewport. When I resize the browser window, the diagram stays small (as expected). Now I want it to fit the viewport again, so I call `viewer.get('canvas').zoom('fit-viewport', 'auto');`.

The problem is, that after the first call, the diagram is not resized as expected. I have to call the function again to make it resize correctly.

![bpmnio_zoom](https://cloud.githubusercontent.com/assets/8982136/7611094/48d66618-f982-11e4-817c-e8fbbc411284.gif)

**Comment by nikku** [comment]
The demo now tells the diagram about the window resize and other applications must do that, too (via `canvas.resized()`. By doing so the diagram will do a number of things, including removing the computed cached view box and responsive resizing of the palette.
