### ISSUE TITLE
Do not scale Popup menu and Context pad with canvas zoom level

### ISSUE THREAD

**Issue by marstamm** [bpmn-io/diagram-js#879]
## Problem
When I am working on a zoomed in canvas, the popup menu is significantly bigger than in a zoomed out state, while not offering more information or options.

![image](https://github.com/bpmn-io/diagram-js/assets/21984219/3d655d5c-b488-4fce-a4db-748fa3d24bba)
![image](https://github.com/bpmn-io/diagram-js/assets/21984219/a142feab-33a0-4f16-9ee1-7a15bfefbda8)

This is also leads to inconsistent UI on the screen, as we do not scale other UI elements, such as the properties panel with the canvas zoom level. We end up with different font- and icon sizes on the screen.

Ideally, I want the popup menu to stay the same size no matter the zoom level to offer a consistent experience.

For this to work, we would also need to keep the context pad from scaling, as it serves the same purpose as the popup menu. Also, we do use both to achieve similar UI to the user, e.g. for the color changer:
![image](https://github.com/bpmn-io/diagram-js/assets/21984219/bc11c888-a111-4dfc-b6b9-afb3ca6e8ce2)

Looking at other tools like miro, the context is also uses window scale instead of canvas scale and stays the same size no matter how far in or out you zoomed.

## Proposal
Let's make "no zoom" the new default. We can keep the zoom configuration for applications that need it, but require them to enable the feature using the scale config.

## Additional Info

Discovered during https://github.com/bpmn-io/diagram-js/pull/878
@marstamm will add this as a topic in the next HOC.

**Comment by marstamm** [comment]
We need to be aware of potential accessibility issues when we do not scale with zoom level, as the desktop modeler does not allow browser zoom. This was already reported as an issue with the current behavior: https://camunda.slack.com/archives/C0693F1NFK5/p1706806565700849

**Comment by nikku** [comment]
I'd like us to keep the existing zoom characteristics, cf. https://github.com/bpmn-io/diagram-js/issues/879#issuecomment-2037258910.

There is a reason you zoom in, and if that is for presentation or focus a UI that adapts (if only slightly!) supports you.

**Comment by philippfromme** [comment]
I think we should allow users to zoom the entire application and not bind the zoom of one (!) single UI element to the zoom of the diagram. UI !== diagram.

**Comment by nikku** [comment]
Let's discuss this tomorrow in our weekly. Core diagram-js offers us all the tools we need, we just need to settle down on something.

**Comment by barmac** [comment]
Bottom-line is that the palette, the context pad, and the popup menu should ideally share the scale while canvas should be handled separately.

**Comment by marstamm** [comment]
In the daily, we decided to disable auto-scaling of the context pad and popup menu
