### ISSUE TITLE
Document and refactor PopupMenu

### ISSUE THREAD

**Issue by ricardomatias** [bpmn-io/diagram-js#88]
The PopupMenu needs to be added to the docs. At the moment it is absent from our documentation, which makes it hard for users to find it and understand what functionality it provides.

**Comment by nikku** [comment]
What happens if the popup is opened again with different entries + position? We need a test case for this and define the expected behavior.

**Comment by nikku** [comment]
In the new implementation the `name` parameter in `PopupMenu#open` is not needed anymore and thus needs to be removed.

**Comment by nikku** [comment]
Ok, looks like the name is still needed as the popup menus className.

**Comment by nikku** [comment]
Using the popup menu in the app throws `TypeError: self._trigger is not a function`.
