### ISSUE TITLE
Dragging preview does not show Connection markers

### ISSUE THREAD

**Issue by marstamm** [bpmn-io/diagram-js#904]
### Describe the Bug

When I drag elements to rearange them, the end marker is not shown

![image](https://github.com/bpmn-io/diagram-js/assets/21984219/1ecd0cb7-a044-4ea8-b3e3-8ef6bc6eeeaf)

### Steps to Reproduce

1. Open https://demo.bpmn.io/s/start
2. Select all
3. Drag around the canvas
4. The preview does not have arrow heads

### Expected Behavior

Similar to pasting, connection end markers should be shown:
![image](https://github.com/bpmn-io/diagram-js/assets/21984219/9eb3c6f1-8491-4d30-b677-3f0865e41dec)

### Environment

Please complete the following information:

 - Browser: Chrome
 - OS: -
 - Library version: dev

### Notes

This happens because `drag.cleanup` is called immediately on start, which cleans up clones markers.

Found during and related to https://github.com/camunda/camunda-modeler/issues/4307

**Comment by nikku** [comment]
:tada:
