### ISSUE TITLE
svg dataset undefined

### ISSUE THREAD

**Issue by Tarrowren** [bpmn-io/diagram-js#911]
### Describe the Bug

>/lib/util/RenderUtil.js
```js
/**
 * @param {Point[]} points
 * @param {number|Object} [attrs]
 * @param {number} [radius]
 *
 * @return {SVGElement}
 */
export function createLine(points, attrs, radius) {
  if (isNumber(attrs)) {
    radius = attrs;
    attrs = null;
  }

  if (!attrs) {
    attrs = {};
  }

  const line = svgCreate("path", attrs);

  if (isNumber(radius)) {
    line.dataset.cornerRadius = String(radius);
  }

  return updateLine(line, points);
}

/**
 * @param {SVGElement} gfx
 * @param {Point[]} points
 *
 * @return {SVGElement}
 */
export function updateLine(gfx, points) {
  const cornerRadius = parseInt(gfx.dataset.cornerRadius, 10) || 0;

  svgAttr(gfx, {
    d: componentsToPath(drawPath(points, cornerRadius)),
  });

  return gfx;
}
```

### Steps to Reproduce

1. do this
2. do that

If possible, try to build [a test case](https://github.com/bpmn-io/diagram-js/tree/main/test/spec) that reproduces your problem.

### Expected Behavior

use `svgAttr`

### Environment

 - Browser: Chrome 60
 - OS: Windows 10
 - Library version: 14.7.0

**Comment by nikku** [comment]
Please provide us with clear steps to reproduce or we cannot help you. As it stands this report is not actionable for us.

**Comment by Tarrowren** [comment]
https://github.com/weolar/miniblink49/releases/download/2019.10.15/miniblink-191015.rar

**Comment by nikku** [comment]
Chrome 60 is from 2017, according to [caniuse](https://caniuse.com/?search=dataset) it supports `dataset` on SVG elements. Even if it did not I wonder why you're forced to stay at a 10 year old browser.

As the given change was made in [v11.9.0](https://github.com/bpmn-io/diagram-js/releases/tag/v11.9.0) I'd suggest you to use a bpmn-js version prior.
