### ISSUE TITLE
Plane elements show up in search results

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/diagram-js#914]
### Describe the Bug

When using search, plane elements show up in the search results. This eventually results in an error when selecting them.

![brave_ACQFyacLja](https://github.com/bpmn-io/diagram-js/assets/7633572/adc2a87d-cd1d-4743-9bc2-ee41fb2d81d3)

### Steps to Reproduce

1. Create a process with a non-empty collapsed sub-process
2. Use search
3. Plane elements show up in search results
4. Selecting them results in an error

### Expected Behavior

Plane elements do not show up in search results.

### Environment

 - Library version: 14.7.1

**Comment by nikku** [comment]
Should be duplicate / upstream bug of https://github.com/bpmn-io/bpmn-js/issues/2143, right?

**Comment by philippfromme** [comment]
@nikku I wasn't aware. Seems to be the same issue, yes.

**Comment by nikku** [comment]
Closing as duplicate; will be fixed via https://github.com/bpmn-io/bpmn-js/issues/2143.
