### ISSUE TITLE
How to customize a bubble card after clicking on a process node？

### ISSUE THREAD

**Issue by tony2y** [bpmn-io/diagram-js#924]
How to customize a bubble card after clicking on a process node, and this bubble card will adaptively pop up along with the node. Probably similar to the element plus Popover component. Is there any implementation method or reference code? Looking forward to your answer!
https://element-plus.org/en-US/component/popover.html
<img width="788" alt="image" src="https://github.com/user-attachments/assets/14000a09-182c-40be-a7ac-0d43b94b506a">
@nikku @philippfromme

**Comment by nikku** [comment]
You can use an [overlay](https://github.com/bpmn-io/bpmn-js-examples/tree/main/overlays) to attach any HTML content relative to an element. Probably possible to implement your bubble card like that.
