### ISSUE TITLE
Extend undo/redo to canvas drag operation

### ISSUE THREAD

**Issue by marcellobarile** [bpmn-io/diagram-js#930]
### Is your feature request related to a problem? Please describe.

Moving the entire diagram around the diagram canvas does not apply undo/redo operation to it.

Initially reported here https://github.com/camunda/web-modeler/pull/10779#issuecomment-2338399100

### Describe the solution you'd like

Executing an `undo` (or `redo`) operation would reset the canvas position to the previous one.

**Comment by nikku** [comment]
I don't know of any application that allows you to undo and redo navigation inside an app. 

What I've seen some do is handle selection as part of the undo/redo stack (examples: Figma, Excalidraw). 

Reached out to the downstream reporters for clarification (https://github.com/camunda/web-modeler/pull/10779#issuecomment-2345664927).

**Comment by nikku** [comment]
Closing as not planned, per https://github.com/camunda/web-modeler/pull/10779#issuecomment-2346181963. The proposed behavior is not present in any known modeling tool.
